//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Genesis_GameClient_NGUILuaFormWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Genesis.GameClient.NGUILuaForm), typeof(Genesis.GameClient.NGUIForm));
		L.RegFunction("OnClickButton", OnClickButton);
		L.RegFunction("GetLinkedPrefab", GetLinkedPrefab);
		L.RegFunction("SubscribeEvent", SubscribeEvent);
		L.RegFunction("UnsubscribeEvent", UnsubscribeEvent);
		L.RegFunction("SetToggleCallback", SetToggleCallback);
		L.RegFunction("SetButtonCallback", SetButtonCallback);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnClickButton(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Genesis.GameClient.NGUILuaForm obj = (Genesis.GameClient.NGUILuaForm)ToLua.CheckObject(L, 1, typeof(Genesis.GameClient.NGUILuaForm));
			string arg0 = ToLua.CheckString(L, 2);
			obj.OnClickButton(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetLinkedPrefab(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Genesis.GameClient.NGUILuaForm obj = (Genesis.GameClient.NGUILuaForm)ToLua.CheckObject(L, 1, typeof(Genesis.GameClient.NGUILuaForm));
			string arg0 = ToLua.CheckString(L, 2);
			UnityEngine.GameObject o = obj.GetLinkedPrefab(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SubscribeEvent(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Genesis.GameClient.NGUILuaForm obj = (Genesis.GameClient.NGUILuaForm)ToLua.CheckObject(L, 1, typeof(Genesis.GameClient.NGUILuaForm));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.SubscribeEvent(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UnsubscribeEvent(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Genesis.GameClient.NGUILuaForm obj = (Genesis.GameClient.NGUILuaForm)ToLua.CheckObject(L, 1, typeof(Genesis.GameClient.NGUILuaForm));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.UnsubscribeEvent(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetToggleCallback(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Genesis.GameClient.NGUILuaForm obj = (Genesis.GameClient.NGUILuaForm)ToLua.CheckObject(L, 1, typeof(Genesis.GameClient.NGUILuaForm));
			UIToggle arg0 = (UIToggle)ToLua.CheckUnityObject(L, 2, typeof(UIToggle));
			obj.SetToggleCallback(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetButtonCallback(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Genesis.GameClient.NGUILuaForm obj = (Genesis.GameClient.NGUILuaForm)ToLua.CheckObject(L, 1, typeof(Genesis.GameClient.NGUILuaForm));
			UIButton arg0 = (UIButton)ToLua.CheckUnityObject(L, 2, typeof(UIButton));
			obj.SetButtonCallback(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

