//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Genesis_GameClient_DataTableProxy_OperationActivityWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Genesis.GameClient.DataTableProxy_OperationActivity), typeof(Genesis.GameClient.DataTableProxy<Genesis.GameClient.DROperationActivity>));
		L.RegFunction("New", _CreateGenesis_GameClient_DataTableProxy_OperationActivity);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateGenesis_GameClient_DataTableProxy_OperationActivity(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				Genesis.GameClient.DataTableProxy_OperationActivity obj = new Genesis.GameClient.DataTableProxy_OperationActivity();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: Genesis.GameClient.DataTableProxy_OperationActivity.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

