//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 1037_CLChangePortrait.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"CLChangePortrait")]
    public partial class CLChangePortrait : PacketBase
    {
        public CLChangePortrait() { }

        public override PacketType PacketType { get { return PacketType.ClientToLobbyServer; } }

        public override int PacketActionId { get { return 1037; } }

        private int m_PortraitType;
        [ProtoMember(1, Name = @"PortraitType", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int PortraitType
        {
            get { return m_PortraitType; }
            set { m_PortraitType = value; }
        }
    }
}
