//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 2701_CLClaimOnlineReward.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"CLClaimOnlineReward")]
    public partial class CLClaimOnlineReward : PacketBase
    {
        public CLClaimOnlineReward() { }

        public override PacketType PacketType { get { return PacketType.ClientToLobbyServer; } }

        public override int PacketActionId { get { return 2701; } }

        private int m_RewardId;
        [ProtoMember(1, Name = @"RewardId", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int RewardId
        {
            get { return m_RewardId; }
            set { m_RewardId = value; }
        }
    }
}
