//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 1062_CLClaimDailyQuestReward.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"CLClaimDailyQuestReward")]
    public partial class CLClaimDailyQuestReward : PacketBase
    {
        public CLClaimDailyQuestReward() { }

        public override PacketType PacketType { get { return PacketType.ClientToLobbyServer; } }

        public override int PacketActionId { get { return 1062; } }

        private int m_DailyQuestId;
        [ProtoMember(1, Name = @"DailyQuestId", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int DailyQuestId
        {
            get { return m_DailyQuestId; }
            set { m_DailyQuestId = value; }
        }
    }
}
