//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 2311_CLGetGift.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"CLGetGift")]
    public partial class CLGetGift : PacketBase
    {
        public CLGetGift() { }

        public override PacketType PacketType { get { return PacketType.ClientToLobbyServer; } }

        public override int PacketActionId { get { return 2311; } }

        private int m_giftId;
        [ProtoMember(1, Name = @"giftId", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int giftId
        {
            get { return m_giftId; }
            set { m_giftId = value; }
        }
    }
}
