//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 1074_CLGetSinglePVPStatus.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"CLGetSinglePVPStatus")]
    public partial class CLGetSinglePVPStatus : PacketBase
    {
        public CLGetSinglePVPStatus() { }

        public override PacketType PacketType { get { return PacketType.ClientToLobbyServer; } }

        public override int PacketActionId { get { return 1074; } }

        private int m_UserId;
        [ProtoMember(1, Name = @"UserId", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int UserId
        {
            get { return m_UserId; }
            set { m_UserId = value; }
        }
    }
}
