//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 999_CLGMCommand.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"CLGMCommand")]
    public partial class CLGMCommand : PacketBase
    {
        public CLGMCommand() { }

        public override PacketType PacketType { get { return PacketType.ClientToLobbyServer; } }

        public override int PacketActionId { get { return 999; } }

        private int m_Type;
        [ProtoMember(1, Name = @"Type", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int Type
        {
            get { return m_Type; }
            set { m_Type = value; }
        }

        private readonly List<string> m_Params = new List<string>();
        [ProtoMember(2, Name = @"Params", DataFormat = DataFormat.Default)]
        public List<string> Params
        {
            get { return m_Params; }
        }
    }
}
