//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 1400_CLIncreaseHeroQualityLevel.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"CLIncreaseHeroQualityLevel")]
    public partial class CLIncreaseHeroQualityLevel : PacketBase
    {
        public CLIncreaseHeroQualityLevel() { }

        public override PacketType PacketType { get { return PacketType.ClientToLobbyServer; } }

        public override int PacketActionId { get { return 1400; } }

        private int m_HeroTypeId;
        [ProtoMember(1, Name = @"HeroTypeId", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int HeroTypeId
        {
            get { return m_HeroTypeId; }
            set { m_HeroTypeId = value; }
        }
    }
}
