//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 1005_CLLeaveInstance.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"CLLeaveInstance")]
    public partial class CLLeaveInstance : PacketBase
    {
        public CLLeaveInstance() { }

        public override PacketType PacketType { get { return PacketType.ClientToLobbyServer; } }

        public override int PacketActionId { get { return 1005; } }

        private int m_InstanceType;
        [ProtoMember(1, Name = @"InstanceType", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int InstanceType
        {
            get { return m_InstanceType; }
            set { m_InstanceType = value; }
        }

        private bool m_Win;
        [ProtoMember(2, Name = @"Win", IsRequired = true, DataFormat = DataFormat.Default)]
        public bool Win
        {
            get { return m_Win; }
            set { m_Win = value; }
        }

        private int m_StarCount;
        [ProtoMember(3, Name = @"StarCount", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int StarCount
        {
            get { return m_StarCount; }
            set { m_StarCount = value; }
        }

        private int m_DropCoins;
        [ProtoMember(4, Name = @"DropCoins", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int DropCoins
        {
            get { return m_DropCoins; }
            set { m_DropCoins = value; }
        }

        private readonly List<PBMonster> m_KillMonsters = new List<PBMonster>();
        [ProtoMember(5, Name = @"KillMonsters", DataFormat = DataFormat.Default)]
        public List<PBMonster> KillMonsters
        {
            get { return m_KillMonsters; }
        }
    }
}
