//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 1408_CLLevelUpSkillBadge.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"CLLevelUpSkillBadge")]
    public partial class CLLevelUpSkillBadge : PacketBase
    {
        public CLLevelUpSkillBadge() { }

        public override PacketType PacketType { get { return PacketType.ClientToLobbyServer; } }

        public override int PacketActionId { get { return 1408; } }

        private int m_SourceBadgeId;
        [ProtoMember(1, Name = @"SourceBadgeId", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int SourceBadgeId
        {
            get { return m_SourceBadgeId; }
            set { m_SourceBadgeId = value; }
        }

        private int m_LevelUpBadgeCount;
        [ProtoMember(2, Name = @"LevelUpBadgeCount", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int LevelUpBadgeCount
        {
            get { return m_LevelUpBadgeCount; }
            set { m_LevelUpBadgeCount = value; }
        }

        private int? m_HeroId;
        [ProtoMember(3, Name = @"HeroId", IsRequired = false, DataFormat = DataFormat.TwosComplement)]
        public int HeroId
        {
            get { return m_HeroId ?? default(int); }
            set { m_HeroId = value; }
        }
        public bool HasHeroId { get { return m_HeroId != null; } }
        private void ResetHeroId() { m_HeroId = null; }
        private bool ShouldSerializeHeroId() { return HasHeroId; }

        private int m_SkillIndex;
        [ProtoMember(4, Name = @"SkillIndex", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int SkillIndex
        {
            get { return m_SkillIndex; }
            set { m_SkillIndex = value; }
        }

        private int m_BadgeSlotCategory;
        [ProtoMember(5, Name = @"BadgeSlotCategory", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int BadgeSlotCategory
        {
            get { return m_BadgeSlotCategory; }
            set { m_BadgeSlotCategory = value; }
        }

        private int? m_GenericBadgeSlotIndex;
        [ProtoMember(6, Name = @"GenericBadgeSlotIndex", IsRequired = false, DataFormat = DataFormat.TwosComplement)]
        public int GenericBadgeSlotIndex
        {
            get { return m_GenericBadgeSlotIndex ?? default(int); }
            set { m_GenericBadgeSlotIndex = value; }
        }
        public bool HasGenericBadgeSlotIndex { get { return m_GenericBadgeSlotIndex != null; } }
        private void ResetGenericBadgeSlotIndex() { m_GenericBadgeSlotIndex = null; }
        private bool ShouldSerializeGenericBadgeSlotIndex() { return HasGenericBadgeSlotIndex; }
    }
}
