//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 2621_CLLeaveInstanceForTower.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"CLLeaveInstanceForTower")]
    public partial class CLLeaveInstanceForTower : PacketBase
    {
        public CLLeaveInstanceForTower() { }

        public override PacketType PacketType { get { return PacketType.ClientToLobbyServer; } }

        public override int PacketActionId { get { return 2621; } }

        private int m_InstanceId;
        [ProtoMember(1, Name = @"InstanceId", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int InstanceId
        {
            get { return m_InstanceId; }
            set { m_InstanceId = value; }
        }

        private bool m_Win;
        [ProtoMember(2, Name = @"Win", IsRequired = true, DataFormat = DataFormat.Default)]
        public bool Win
        {
            get { return m_Win; }
            set { m_Win = value; }
        }
    }
}
