//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 2601_CLLeaveInstanceForResource.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"CLLeaveInstanceForResource")]
    public partial class CLLeaveInstanceForResource : PacketBase
    {
        public CLLeaveInstanceForResource() { }

        public override PacketType PacketType { get { return PacketType.ClientToLobbyServer; } }

        public override int PacketActionId { get { return 2601; } }

        private int m_InstanceForResourceId;
        [ProtoMember(1, Name = @"InstanceForResourceId", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int InstanceForResourceId
        {
            get { return m_InstanceForResourceId; }
            set { m_InstanceForResourceId = value; }
        }

        private bool m_Win;
        [ProtoMember(2, Name = @"Win", IsRequired = true, DataFormat = DataFormat.Default)]
        public bool Win
        {
            get { return m_Win; }
            set { m_Win = value; }
        }

        private int? m_RewardLevel;
        [ProtoMember(3, Name = @"RewardLevel", IsRequired = false, DataFormat = DataFormat.TwosComplement)]
        public int RewardLevel
        {
            get { return m_RewardLevel ?? default(int); }
            set { m_RewardLevel = value; }
        }
        public bool HasRewardLevel { get { return m_RewardLevel != null; } }
        private void ResetRewardLevel() { m_RewardLevel = null; }
        private bool ShouldSerializeRewardLevel() { return HasRewardLevel; }

        private int m_DropCoins;
        [ProtoMember(4, Name = @"DropCoins", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int DropCoins
        {
            get { return m_DropCoins; }
            set { m_DropCoins = value; }
        }
    }
}
