//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 3000_CLLogReport.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"CLLogReport")]
    public partial class CLLogReport : PacketBase
    {
        public CLLogReport() { }

        public override PacketType PacketType { get { return PacketType.ClientToLobbyServer; } }

        public override int PacketActionId { get { return 3000; } }

        private int m_Type;
        [ProtoMember(1, Name = @"Type", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int Type
        {
            get { return m_Type; }
            set { m_Type = value; }
        }

        private string m_Message;
        [ProtoMember(2, Name = @"Message", IsRequired = false, DataFormat = DataFormat.Default)]
        public string Message
        {
            get { return m_Message ?? ""; }
            set { m_Message = value; }
        }
        public bool HasMessage { get { return m_Message != null; } }
        private void ResetMessage() { m_Message = null; }
        private bool ShouldSerializeMessage() { return HasMessage; }

        private readonly List<PBKeyValuePair> m_Params = new List<PBKeyValuePair>();
        [ProtoMember(3, Name = @"Params", DataFormat = DataFormat.Default)]
        public List<PBKeyValuePair> Params
        {
            get { return m_Params; }
        }
    }
}
