//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 1102_CLPurchaseInShop.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"CLPurchaseInShop")]
    public partial class CLPurchaseInShop : PacketBase
    {
        public CLPurchaseInShop() { }

        public override PacketType PacketType { get { return PacketType.ClientToLobbyServer; } }

        public override int PacketActionId { get { return 1102; } }

        private int m_ShopType;
        [ProtoMember(1, Name = @"ShopType", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int ShopType
        {
            get { return m_ShopType; }
            set { m_ShopType = value; }
        }

        private int m_ShopItemIndex;
        [ProtoMember(2, Name = @"ShopItemIndex", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int ShopItemIndex
        {
            get { return m_ShopItemIndex; }
            set { m_ShopItemIndex = value; }
        }
    }
}
