//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 1101_CLRefreshShop.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"CLRefreshShop")]
    public partial class CLRefreshShop : PacketBase
    {
        public CLRefreshShop() { }

        public override PacketType PacketType { get { return PacketType.ClientToLobbyServer; } }

        public override int PacketActionId { get { return 1101; } }

        private int m_ShopType;
        [ProtoMember(1, Name = @"ShopType", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int ShopType
        {
            get { return m_ShopType; }
            set { m_ShopType = value; }
        }
    }
}
