//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 3401_CLRefreshRankList.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"CLRefreshRankList")]
    public partial class CLRefreshRankList : PacketBase
    {
        public CLRefreshRankList() { }

        public override PacketType PacketType { get { return PacketType.ClientToLobbyServer; } }

        public override int PacketActionId { get { return 3401; } }

        private int m_RankType;
        [ProtoMember(1, Name = @"RankType", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int RankType
        {
            get { return m_RankType; }
            set { m_RankType = value; }
        }

        private int? m_Index;
        [ProtoMember(2, Name = @"Index", IsRequired = false, DataFormat = DataFormat.TwosComplement)]
        public int Index
        {
            get { return m_Index ?? default(int); }
            set { m_Index = value; }
        }
        public bool HasIndex { get { return m_Index != null; } }
        private void ResetIndex() { m_Index = null; }
        private bool ShouldSerializeIndex() { return HasIndex; }

        private int? m_Count;
        [ProtoMember(3, Name = @"Count", IsRequired = false, DataFormat = DataFormat.TwosComplement)]
        public int Count
        {
            get { return m_Count ?? default(int); }
            set { m_Count = value; }
        }
        public bool HasCount { get { return m_Count != null; } }
        private void ResetCount() { m_Count = null; }
        private bool ShouldSerializeCount() { return HasCount; }
    }
}
