//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 3001_CLSendChat.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"CLSendChat")]
    public partial class CLSendChat : PacketBase
    {
        public CLSendChat() { }

        public override PacketType PacketType { get { return PacketType.ClientToLobbyServer; } }

        public override int PacketActionId { get { return 3001; } }

        private int m_Channel;
        [ProtoMember(1, Name = @"Channel", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int Channel
        {
            get { return m_Channel; }
            set { m_Channel = value; }
        }

        private int? m_ReceiverPlayerId;
        [ProtoMember(2, Name = @"ReceiverPlayerId", IsRequired = false, DataFormat = DataFormat.TwosComplement)]
        public int ReceiverPlayerId
        {
            get { return m_ReceiverPlayerId ?? default(int); }
            set { m_ReceiverPlayerId = value; }
        }
        public bool HasReceiverPlayerId { get { return m_ReceiverPlayerId != null; } }
        private void ResetReceiverPlayerId() { m_ReceiverPlayerId = null; }
        private bool ShouldSerializeReceiverPlayerId() { return HasReceiverPlayerId; }

        private string m_Message;
        [ProtoMember(3, Name = @"Message", IsRequired = true, DataFormat = DataFormat.Default)]
        public string Message
        {
            get { return m_Message; }
            set { m_Message = value; }
        }
    }
}
