//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 3101_CLSearchPlayers.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"CLSearchPlayers")]
    public partial class CLSearchPlayers : PacketBase
    {
        public CLSearchPlayers() { }

        public override PacketType PacketType { get { return PacketType.ClientToLobbyServer; } }

        public override int PacketActionId { get { return 3101; } }

        private string m_Keyword;
        [ProtoMember(1, Name = @"Keyword", IsRequired = true, DataFormat = DataFormat.Default)]
        public string Keyword
        {
            get { return m_Keyword; }
            set { m_Keyword = value; }
        }

        private int? m_UserId;
        [ProtoMember(2, Name = @"UserId", IsRequired = false, DataFormat = DataFormat.TwosComplement)]
        public int UserId
        {
            get { return m_UserId ?? default(int); }
            set { m_UserId = value; }
        }
        public bool HasUserId { get { return m_UserId != null; } }
        private void ResetUserId() { m_UserId = null; }
        private bool ShouldSerializeUserId() { return HasUserId; }
    }
}
