//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 1008_CLUpdatePosition.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"CLUpdatePosition")]
    public partial class CLUpdatePosition : PacketBase
    {
        public CLUpdatePosition() { }

        public override PacketType PacketType { get { return PacketType.ClientToLobbyServer; } }

        public override int PacketActionId { get { return 1008; } }

        private PBVector2 m_Position;
        [ProtoMember(1, Name = @"Position", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBVector2 Position
        {
            get { return m_Position; }
            set { m_Position = value; }
        }
    }
}
