//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 1401_CLUseHeroQualityItem.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"CLUseHeroQualityItem")]
    public partial class CLUseHeroQualityItem : PacketBase
    {
        public CLUseHeroQualityItem() { }

        public override PacketType PacketType { get { return PacketType.ClientToLobbyServer; } }

        public override int PacketActionId { get { return 1401; } }

        private int m_HeroTypeId;
        [ProtoMember(1, Name = @"HeroTypeId", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int HeroTypeId
        {
            get { return m_HeroTypeId; }
            set { m_HeroTypeId = value; }
        }

        private int m_QualityItemSlotIndex;
        [ProtoMember(2, Name = @"QualityItemSlotIndex", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int QualityItemSlotIndex
        {
            get { return m_QualityItemSlotIndex; }
            set { m_QualityItemSlotIndex = value; }
        }
    }
}
