//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 2309_LCBuyItemResult.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"LCBuyItemResult")]
    public partial class LCBuyItemResult : PacketBase
    {
        public LCBuyItemResult() { }

        public override PacketType PacketType { get { return PacketType.LobbyServerToClient; } }

        public override int PacketActionId { get { return 2309; } }

        private readonly List<PBCompoundItemInfo> m_CompoundItemInfo = new List<PBCompoundItemInfo>();
        [ProtoMember(1, Name = @"CompoundItemInfo", DataFormat = DataFormat.Default)]
        public List<PBCompoundItemInfo> CompoundItemInfo
        {
            get { return m_CompoundItemInfo; }
        }
    }
}
