//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 2308_LCBuyAdditionalArenaCount.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"LCBuyAdditionalArenaCount")]
    public partial class LCBuyAdditionalArenaCount : PacketBase
    {
        public LCBuyAdditionalArenaCount() { }

        public override PacketType PacketType { get { return PacketType.LobbyServerToClient; } }

        public override int PacketActionId { get { return 2308; } }

        private PBPlayerInfo m_PlayerInfo = null;
        [ProtoMember(1, Name = @"PlayerInfo", IsRequired = false, DataFormat = DataFormat.Default)]
        [System.ComponentModel.DefaultValue(null)]
        public PBPlayerInfo PlayerInfo
        {
            get { return m_PlayerInfo; }
            set { m_PlayerInfo = value; }
        }

        private int m_TodayBuyAdditionalArenaCount;
        [ProtoMember(2, Name = @"TodayBuyAdditionalArenaCount", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int TodayBuyAdditionalArenaCount
        {
            get { return m_TodayBuyAdditionalArenaCount; }
            set { m_TodayBuyAdditionalArenaCount = value; }
        }
    }
}
