//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 1009_LCChangeHeroTeam.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"LCChangeHeroTeam")]
    public partial class LCChangeHeroTeam : PacketBase
    {
        public LCChangeHeroTeam() { }

        public override PacketType PacketType { get { return PacketType.LobbyServerToClient; } }

        public override int PacketActionId { get { return 1009; } }

        private PBHeroTeamInfo m_HeroTeamInfo;
        [ProtoMember(1, Name = @"HeroTeamInfo", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBHeroTeamInfo HeroTeamInfo
        {
            get { return m_HeroTeamInfo; }
            set { m_HeroTeamInfo = value; }
        }

        private PBPlayerInfo m_PlayerInfo = null;
        [ProtoMember(2, Name = @"PlayerInfo", IsRequired = false, DataFormat = DataFormat.Default)]
        [System.ComponentModel.DefaultValue(null)]
        public PBPlayerInfo PlayerInfo
        {
            get { return m_PlayerInfo; }
            set { m_PlayerInfo = value; }
        }
    }
}
