//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 2702_LCClaimSevenDayLoginReward.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"LCClaimSevenDayLoginReward")]
    public partial class LCClaimSevenDayLoginReward : PacketBase
    {
        public LCClaimSevenDayLoginReward() { }

        public override PacketType PacketType { get { return PacketType.LobbyServerToClient; } }

        public override int PacketActionId { get { return 2702; } }

        private PBSevenDayLoginInfo m_SevenDayLoginInfo;
        [ProtoMember(1, Name = @"SevenDayLoginInfo", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBSevenDayLoginInfo SevenDayLoginInfo
        {
            get { return m_SevenDayLoginInfo; }
            set { m_SevenDayLoginInfo = value; }
        }
    }
}
