//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 3107_LCClaimEnergy.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"LCClaimEnergy")]
    public partial class LCClaimEnergy : PacketBase
    {
        public LCClaimEnergy() { }

        public override PacketType PacketType { get { return PacketType.LobbyServerToClient; } }

        public override int PacketActionId { get { return 3107; } }

        private int m_TodayClaimCount;
        [ProtoMember(1, Name = @"TodayClaimCount", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int TodayClaimCount
        {
            get { return m_TodayClaimCount; }
            set { m_TodayClaimCount = value; }
        }

        private PBPlayerInfo m_PlayerInfo;
        [ProtoMember(2, Name = @"PlayerInfo", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBPlayerInfo PlayerInfo
        {
            get { return m_PlayerInfo; }
            set { m_PlayerInfo = value; }
        }

        private PBFriendInfo m_FriendInfo;
        [ProtoMember(3, Name = @"FriendInfo", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBFriendInfo FriendInfo
        {
            get { return m_FriendInfo; }
            set { m_FriendInfo = value; }
        }
    }
}
