//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 1063_LCClaimActivenessChest.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"LCClaimActivenessChest")]
    public partial class LCClaimActivenessChest : PacketBase
    {
        public LCClaimActivenessChest() { }

        public override PacketType PacketType { get { return PacketType.LobbyServerToClient; } }

        public override int PacketActionId { get { return 1063; } }

        private int m_ChestId;
        [ProtoMember(1, Name = @"ChestId", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int ChestId
        {
            get { return m_ChestId; }
            set { m_ChestId = value; }
        }

        private PBDailyQuestActivenessInfo m_DailyQuestActivenessInfo;
        [ProtoMember(2, Name = @"DailyQuestActivenessInfo", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBDailyQuestActivenessInfo DailyQuestActivenessInfo
        {
            get { return m_DailyQuestActivenessInfo; }
            set { m_DailyQuestActivenessInfo = value; }
        }

        private readonly List<PBCompoundItemInfo> m_CompoundItemInfo = new List<PBCompoundItemInfo>();
        [ProtoMember(3, Name = @"CompoundItemInfo", DataFormat = DataFormat.Default)]
        public List<PBCompoundItemInfo> CompoundItemInfo
        {
            get { return m_CompoundItemInfo; }
        }
    }
}
