//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 2622_LCClaimRewardsForTower.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"LCClaimRewardsForTower")]
    public partial class LCClaimRewardsForTower : PacketBase
    {
        public LCClaimRewardsForTower() { }

        public override PacketType PacketType { get { return PacketType.LobbyServerToClient; } }

        public override int PacketActionId { get { return 2622; } }

        private PBInstanceForTowerInfo m_InstanceForTowerInfo;
        [ProtoMember(1, Name = @"InstanceForTowerInfo", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBInstanceForTowerInfo InstanceForTowerInfo
        {
            get { return m_InstanceForTowerInfo; }
            set { m_InstanceForTowerInfo = value; }
        }
    }
}
