//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 2600_LCEnterInstanceForResource.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"LCEnterInstanceForResource")]
    public partial class LCEnterInstanceForResource : PacketBase
    {
        public LCEnterInstanceForResource() { }

        public override PacketType PacketType { get { return PacketType.LobbyServerToClient; } }

        public override int PacketActionId { get { return 2600; } }

        private int m_InstanceForResourceId;
        [ProtoMember(1, Name = @"InstanceForResourceId", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int InstanceForResourceId
        {
            get { return m_InstanceForResourceId; }
            set { m_InstanceForResourceId = value; }
        }

        private int m_PlayedCount;
        [ProtoMember(2, Name = @"PlayedCount", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int PlayedCount
        {
            get { return m_PlayedCount; }
            set { m_PlayedCount = value; }
        }
    }
}
