//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 1072_LCGetSinglePvpRank.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"LCGetSinglePvpRank")]
    public partial class LCGetSinglePvpRank : PacketBase
    {
        public LCGetSinglePvpRank() { }

        public override PacketType PacketType { get { return PacketType.LobbyServerToClient; } }

        public override int PacketActionId { get { return 1072; } }

        private int m_Score;
        [ProtoMember(1, Name = @"Score", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int Score
        {
            get { return m_Score; }
            set { m_Score = value; }
        }
    }
}
