//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 3300_LCGetOnlineStatus.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"LCGetOnlineStatus")]
    public partial class LCGetOnlineStatus : PacketBase
    {
        public LCGetOnlineStatus() { }

        public override PacketType PacketType { get { return PacketType.LobbyServerToClient; } }

        public override int PacketActionId { get { return 3300; } }

        private readonly List<PBOnlineStatus> m_OnlineStatus = new List<PBOnlineStatus>();
        [ProtoMember(1, Name = @"OnlineStatus", DataFormat = DataFormat.Default)]
        public List<PBOnlineStatus> OnlineStatus
        {
            get { return m_OnlineStatus; }
        }
    }
}
