//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 2700_LCGetItemStatus.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"LCGetItemStatus")]
    public partial class LCGetItemStatus : PacketBase
    {
        public LCGetItemStatus() { }

        public override PacketType PacketType { get { return PacketType.LobbyServerToClient; } }

        public override int PacketActionId { get { return 2700; } }

        private readonly List<int> m_firstCharges = new List<int>();
        [ProtoMember(1, Name = @"firstCharges", DataFormat = DataFormat.TwosComplement)]
        public List<int> firstCharges
        {
            get { return m_firstCharges; }
        }

        private readonly List<PBGiftInfo> m_giftInfo = new List<PBGiftInfo>();
        [ProtoMember(2, Name = @"giftInfo", DataFormat = DataFormat.Default)]
        public List<PBGiftInfo> giftInfo
        {
            get { return m_giftInfo; }
        }
    }
}
