//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 1010_LCHeroStarLevelUp.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"LCHeroStarLevelUp")]
    public partial class LCHeroStarLevelUp : PacketBase
    {
        public LCHeroStarLevelUp() { }

        public override PacketType PacketType { get { return PacketType.LobbyServerToClient; } }

        public override int PacketActionId { get { return 1010; } }

        private PBLobbyHeroInfo m_LobbyHeroInfo;
        [ProtoMember(1, Name = @"LobbyHeroInfo", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBLobbyHeroInfo LobbyHeroInfo
        {
            get { return m_LobbyHeroInfo; }
            set { m_LobbyHeroInfo = value; }
        }

        private PBItemInfo m_ItemInfo;
        [ProtoMember(2, Name = @"ItemInfo", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBItemInfo ItemInfo
        {
            get { return m_ItemInfo; }
            set { m_ItemInfo = value; }
        }

        private PBPlayerInfo m_PlayerInfo;
        [ProtoMember(3, Name = @"PlayerInfo", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBPlayerInfo PlayerInfo
        {
            get { return m_PlayerInfo; }
            set { m_PlayerInfo = value; }
        }
    }
}
