//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 1406_LCInsertSkillBadge.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"LCInsertSkillBadge")]
    public partial class LCInsertSkillBadge : PacketBase
    {
        public LCInsertSkillBadge() { }

        public override PacketType PacketType { get { return PacketType.LobbyServerToClient; } }

        public override int PacketActionId { get { return 1406; } }

        private PBLobbyHeroInfo m_HeroInfo;
        [ProtoMember(1, Name = @"HeroInfo", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBLobbyHeroInfo HeroInfo
        {
            get { return m_HeroInfo; }
            set { m_HeroInfo = value; }
        }

        private readonly List<PBItemInfo> m_BadgeItemInfos = new List<PBItemInfo>();
        [ProtoMember(2, Name = @"BadgeItemInfos", DataFormat = DataFormat.Default)]
        public List<PBItemInfo> BadgeItemInfos
        {
            get { return m_BadgeItemInfos; }
        }

        private PBPlayerInfo m_PlayerInfo;
        [ProtoMember(3, Name = @"PlayerInfo", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBPlayerInfo PlayerInfo
        {
            get { return m_PlayerInfo; }
            set { m_PlayerInfo = value; }
        }
    }
}
