//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 1408_LCLevelUpSkillBadge.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"LCLevelUpSkillBadge")]
    public partial class LCLevelUpSkillBadge : PacketBase
    {
        public LCLevelUpSkillBadge() { }

        public override PacketType PacketType { get { return PacketType.LobbyServerToClient; } }

        public override int PacketActionId { get { return 1408; } }

        private readonly List<PBItemInfo> m_BadgeItemsData = new List<PBItemInfo>();
        [ProtoMember(1, Name = @"BadgeItemsData", DataFormat = DataFormat.Default)]
        public List<PBItemInfo> BadgeItemsData
        {
            get { return m_BadgeItemsData; }
        }

        private PBPlayerInfo m_PlayerInfo;
        [ProtoMember(2, Name = @"PlayerInfo", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBPlayerInfo PlayerInfo
        {
            get { return m_PlayerInfo; }
            set { m_PlayerInfo = value; }
        }

        private PBLobbyHeroInfo m_HeroInfo = null;
        [ProtoMember(3, Name = @"HeroInfo", IsRequired = false, DataFormat = DataFormat.Default)]
        [System.ComponentModel.DefaultValue(null)]
        public PBLobbyHeroInfo HeroInfo
        {
            get { return m_HeroInfo; }
            set { m_HeroInfo = value; }
        }
    }
}
