//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 3200_LCNewMail.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"LCNewMail")]
    public partial class LCNewMail : PacketBase
    {
        public LCNewMail() { }

        public override PacketType PacketType { get { return PacketType.LobbyServerToClient; } }

        public override int PacketActionId { get { return 3200; } }

        private PBMailInfo m_NewMail;
        [ProtoMember(1, Name = @"NewMail", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBMailInfo NewMail
        {
            get { return m_NewMail; }
            set { m_NewMail = value; }
        }
    }
}
