//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 2202_LCOpenAllChances.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"LCOpenAllChances")]
    public partial class LCOpenAllChances : PacketBase
    {
        public LCOpenAllChances() { }

        public override PacketType PacketType { get { return PacketType.LobbyServerToClient; } }

        public override int PacketActionId { get { return 2202; } }

        private int m_ChanceType;
        [ProtoMember(1, Name = @"ChanceType", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int ChanceType
        {
            get { return m_ChanceType; }
            set { m_ChanceType = value; }
        }

        private readonly List<int> m_OpenedRealIndices = new List<int>();
        [ProtoMember(2, Name = @"OpenedRealIndices", DataFormat = DataFormat.TwosComplement)]
        public List<int> OpenedRealIndices
        {
            get { return m_OpenedRealIndices; }
        }

        private readonly List<PBChanceItem> m_OpenedChanceItems = new List<PBChanceItem>();
        [ProtoMember(3, Name = @"OpenedChanceItems", DataFormat = DataFormat.Default)]
        public List<PBChanceItem> OpenedChanceItems
        {
            get { return m_OpenedChanceItems; }
        }

        private PBPlayerInfo m_PlayerInfo;
        [ProtoMember(4, Name = @"PlayerInfo", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBPlayerInfo PlayerInfo
        {
            get { return m_PlayerInfo; }
            set { m_PlayerInfo = value; }
        }

        private readonly List<PBCompoundItemInfo> m_CompoundItemInfo = new List<PBCompoundItemInfo>();
        [ProtoMember(5, Name = @"CompoundItemInfo", DataFormat = DataFormat.Default)]
        public List<PBCompoundItemInfo> CompoundItemInfo
        {
            get { return m_CompoundItemInfo; }
        }
    }
}
