//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 2602_LCResetInstancesForResource.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"LCResetInstancesForResource")]
    public partial class LCResetInstancesForResource : PacketBase
    {
        public LCResetInstancesForResource() { }

        public override PacketType PacketType { get { return PacketType.LobbyServerToClient; } }

        public override int PacketActionId { get { return 2602; } }

        private PBInstanceForCoinResourceInfo m_InstanceForCoinResource;
        [ProtoMember(1, Name = @"InstanceForCoinResource", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBInstanceForCoinResourceInfo InstanceForCoinResource
        {
            get { return m_InstanceForCoinResource; }
            set { m_InstanceForCoinResource = value; }
        }

        private PBInstanceForExpResourceInfo m_InstanceForExpResource;
        [ProtoMember(2, Name = @"InstanceForExpResource", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBInstanceForExpResourceInfo InstanceForExpResource
        {
            get { return m_InstanceForExpResource; }
            set { m_InstanceForExpResource = value; }
        }
    }
}
