//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 3201_LCReadMail.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"LCReadMail")]
    public partial class LCReadMail : PacketBase
    {
        public LCReadMail() { }

        public override PacketType PacketType { get { return PacketType.LobbyServerToClient; } }

        public override int PacketActionId { get { return 3201; } }

        private readonly List<int> m_MailIds = new List<int>();
        [ProtoMember(1, Name = @"MailIds", DataFormat = DataFormat.TwosComplement)]
        public List<int> MailIds
        {
            get { return m_MailIds; }
        }

        private readonly List<PBCompoundItemInfo> m_CompoundItemInfo = new List<PBCompoundItemInfo>();
        [ProtoMember(2, Name = @"CompoundItemInfo", DataFormat = DataFormat.Default)]
        public List<PBCompoundItemInfo> CompoundItemInfo
        {
            get { return m_CompoundItemInfo; }
        }
    }
}
