//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 1076_LCRetroactiveDailyLogin.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"LCRetroactiveDailyLogin")]
    public partial class LCRetroactiveDailyLogin : PacketBase
    {
        public LCRetroactiveDailyLogin() { }

        public override PacketType PacketType { get { return PacketType.LobbyServerToClient; } }

        public override int PacketActionId { get { return 1076; } }

        private int m_day;
        [ProtoMember(1, Name = @"day", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int day
        {
            get { return m_day; }
            set { m_day = value; }
        }
    }
}
