//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 3302_LCRefreshNearbyPlayers.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"LCRefreshNearbyPlayers")]
    public partial class LCRefreshNearbyPlayers : PacketBase
    {
        public LCRefreshNearbyPlayers() { }

        public override PacketType PacketType { get { return PacketType.LobbyServerToClient; } }

        public override int PacketActionId { get { return 3302; } }

        private readonly List<int> m_ReserveNearbyPlayerIds = new List<int>();
        [ProtoMember(1, Name = @"ReserveNearbyPlayerIds", DataFormat = DataFormat.TwosComplement)]
        public List<int> ReserveNearbyPlayerIds
        {
            get { return m_ReserveNearbyPlayerIds; }
        }

        private readonly List<PBNearbyPlayerInfo> m_NewNearbyPlayers = new List<PBNearbyPlayerInfo>();
        [ProtoMember(2, Name = @"NewNearbyPlayers", DataFormat = DataFormat.Default)]
        public List<PBNearbyPlayerInfo> NewNearbyPlayers
        {
            get { return m_NewNearbyPlayers; }
        }
    }
}
