//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 1070_LCResetDailyLogin.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"LCResetDailyLogin")]
    public partial class LCResetDailyLogin : PacketBase
    {
        public LCResetDailyLogin() { }

        public override PacketType PacketType { get { return PacketType.LobbyServerToClient; } }

        public override int PacketActionId { get { return 1070; } }

        private PBDailyLoginInfo m_DailyLoginInfo;
        [ProtoMember(1, Name = @"DailyLoginInfo", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBDailyLoginInfo DailyLoginInfo
        {
            get { return m_DailyLoginInfo; }
            set { m_DailyLoginInfo = value; }
        }
    }
}
