//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 2307_LCResetArena.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"LCResetArena")]
    public partial class LCResetArena : PacketBase
    {
        public LCResetArena() { }

        public override PacketType PacketType { get { return PacketType.LobbyServerToClient; } }

        public override int PacketActionId { get { return 2307; } }

        private int m_PlayArenaCount;
        [ProtoMember(1, Name = @"PlayArenaCount", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int PlayArenaCount
        {
            get { return m_PlayArenaCount; }
            set { m_PlayArenaCount = value; }
        }

        private int m_RefreshArenaCount;
        [ProtoMember(2, Name = @"RefreshArenaCount", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int RefreshArenaCount
        {
            get { return m_RefreshArenaCount; }
            set { m_RefreshArenaCount = value; }
        }

        private int m_BuyAdditionalArenaCount;
        [ProtoMember(3, Name = @"BuyAdditionalArenaCount", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int BuyAdditionalArenaCount
        {
            get { return m_BuyAdditionalArenaCount; }
            set { m_BuyAdditionalArenaCount = value; }
        }
    }
}
