//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 3108_LCResetFriendEnergy.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"LCResetFriendEnergy")]
    public partial class LCResetFriendEnergy : PacketBase
    {
        public LCResetFriendEnergy() { }

        public override PacketType PacketType { get { return PacketType.LobbyServerToClient; } }

        public override int PacketActionId { get { return 3108; } }

        private PBFriendEnergy m_FriendEnergy;
        [ProtoMember(1, Name = @"FriendEnergy", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBFriendEnergy FriendEnergy
        {
            get { return m_FriendEnergy; }
            set { m_FriendEnergy = value; }
        }
    }
}
