//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 3001_LCSendChat.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"LCSendChat")]
    public partial class LCSendChat : PacketBase
    {
        public LCSendChat() { }

        public override PacketType PacketType { get { return PacketType.LobbyServerToClient; } }

        public override int PacketActionId { get { return 3001; } }

        private int m_Channel;
        [ProtoMember(1, Name = @"Channel", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int Channel
        {
            get { return m_Channel; }
            set { m_Channel = value; }
        }

        private PBPlayerInfo m_Receiver = null;
        [ProtoMember(2, Name = @"Receiver", IsRequired = false, DataFormat = DataFormat.Default)]
        [System.ComponentModel.DefaultValue(null)]
        public PBPlayerInfo Receiver
        {
            get { return m_Receiver; }
            set { m_Receiver = value; }
        }

        private string m_Message;
        [ProtoMember(3, Name = @"Message", IsRequired = true, DataFormat = DataFormat.Default)]
        public string Message
        {
            get { return m_Message; }
            set { m_Message = value; }
        }

        private PBInt64 m_Time;
        [ProtoMember(4, Name = @"Time", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBInt64 Time
        {
            get { return m_Time; }
            set { m_Time = value; }
        }
    }
}
