//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 1003_LCSignIn.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"LCSignIn")]
    public partial class LCSignIn : PacketBase
    {
        public LCSignIn() { }

        public override PacketType PacketType { get { return PacketType.LobbyServerToClient; } }

        public override int PacketActionId { get { return 1003; } }

        private readonly List<PBServerConfigInfo> m_ServerConfigInfo = new List<PBServerConfigInfo>();
        [ProtoMember(1, Name = @"ServerConfigInfo", DataFormat = DataFormat.Default)]
        public List<PBServerConfigInfo> ServerConfigInfo
        {
            get { return m_ServerConfigInfo; }
        }

        private PBPlayerInfo m_PlayerInfo;
        [ProtoMember(2, Name = @"PlayerInfo", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBPlayerInfo PlayerInfo
        {
            get { return m_PlayerInfo; }
            set { m_PlayerInfo = value; }
        }

        private readonly List<PBLobbyHeroInfo> m_LobbyHeroInfo = new List<PBLobbyHeroInfo>();
        [ProtoMember(3, Name = @"LobbyHeroInfo", DataFormat = DataFormat.Default)]
        public List<PBLobbyHeroInfo> LobbyHeroInfo
        {
            get { return m_LobbyHeroInfo; }
        }

        private readonly List<PBHeroTeamInfo> m_HeroTeamInfo = new List<PBHeroTeamInfo>();
        [ProtoMember(4, Name = @"HeroTeamInfo", DataFormat = DataFormat.Default)]
        public List<PBHeroTeamInfo> HeroTeamInfo
        {
            get { return m_HeroTeamInfo; }
        }

        private readonly List<PBInstanceProgressInfo> m_InstanceProgressInfo = new List<PBInstanceProgressInfo>();
        [ProtoMember(5, Name = @"InstanceProgressInfo", DataFormat = DataFormat.Default)]
        public List<PBInstanceProgressInfo> InstanceProgressInfo
        {
            get { return m_InstanceProgressInfo; }
        }

        private readonly List<PBInstanceGroupChestStatus> m_InstanceGroupChestStatus = new List<PBInstanceGroupChestStatus>();
        [ProtoMember(6, Name = @"InstanceGroupChestStatus", DataFormat = DataFormat.Default)]
        public List<PBInstanceGroupChestStatus> InstanceGroupChestStatus
        {
            get { return m_InstanceGroupChestStatus; }
        }

        private PBMeridianInfo m_MeridianInfo;
        [ProtoMember(7, Name = @"MeridianInfo", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBMeridianInfo MeridianInfo
        {
            get { return m_MeridianInfo; }
            set { m_MeridianInfo = value; }
        }

        private readonly List<PBItemInfo> m_ItemInfo = new List<PBItemInfo>();
        [ProtoMember(8, Name = @"ItemInfo", DataFormat = DataFormat.Default)]
        public List<PBItemInfo> ItemInfo
        {
            get { return m_ItemInfo; }
        }

        private readonly List<PBFriendInfo> m_FriendInfo = new List<PBFriendInfo>();
        [ProtoMember(9, Name = @"FriendInfo", DataFormat = DataFormat.Default)]
        public List<PBFriendInfo> FriendInfo
        {
            get { return m_FriendInfo; }
        }

        private readonly List<PBPlayerInfo> m_FriendRequestInfo = new List<PBPlayerInfo>();
        [ProtoMember(10, Name = @"FriendRequestInfo", DataFormat = DataFormat.Default)]
        public List<PBPlayerInfo> FriendRequestInfo
        {
            get { return m_FriendRequestInfo; }
        }

        private PBFriendEnergy m_FriendEnergyInfo;
        [ProtoMember(11, Name = @"FriendEnergyInfo", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBFriendEnergy FriendEnergyInfo
        {
            get { return m_FriendEnergyInfo; }
            set { m_FriendEnergyInfo = value; }
        }

        private readonly List<PBMailInfo> m_MailInfo = new List<PBMailInfo>();
        [ProtoMember(12, Name = @"MailInfo", DataFormat = DataFormat.Default)]
        public List<PBMailInfo> MailInfo
        {
            get { return m_MailInfo; }
        }

        private readonly List<PBShopInfo> m_ShopInfo = new List<PBShopInfo>();
        [ProtoMember(13, Name = @"ShopInfo", DataFormat = DataFormat.Default)]
        public List<PBShopInfo> ShopInfo
        {
            get { return m_ShopInfo; }
        }

        private readonly List<PBChanceInfo> m_ChanceInfo = new List<PBChanceInfo>();
        [ProtoMember(14, Name = @"ChanceInfo", DataFormat = DataFormat.Default)]
        public List<PBChanceInfo> ChanceInfo
        {
            get { return m_ChanceInfo; }
        }

        private readonly List<PBAchievementInfo> m_AchievementInfo = new List<PBAchievementInfo>();
        [ProtoMember(15, Name = @"AchievementInfo", DataFormat = DataFormat.Default)]
        public List<PBAchievementInfo> AchievementInfo
        {
            get { return m_AchievementInfo; }
        }

        private readonly List<PBDailyQuestInfo> m_DailyQuestInfo = new List<PBDailyQuestInfo>();
        [ProtoMember(16, Name = @"DailyQuestInfo", DataFormat = DataFormat.Default)]
        public List<PBDailyQuestInfo> DailyQuestInfo
        {
            get { return m_DailyQuestInfo; }
        }

        private PBDailyQuestActivenessInfo m_DailyQuestActivenessInfo;
        [ProtoMember(17, Name = @"DailyQuestActivenessInfo", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBDailyQuestActivenessInfo DailyQuestActivenessInfo
        {
            get { return m_DailyQuestActivenessInfo; }
            set { m_DailyQuestActivenessInfo = value; }
        }

        private PBDailyLoginInfo m_DailyLoginInfo;
        [ProtoMember(18, Name = @"DailyLoginInfo", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBDailyLoginInfo DailyLoginInfo
        {
            get { return m_DailyLoginInfo; }
            set { m_DailyLoginInfo = value; }
        }

        private PBVipInfo m_VipInfo;
        [ProtoMember(19, Name = @"VipInfo", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBVipInfo VipInfo
        {
            get { return m_VipInfo; }
            set { m_VipInfo = value; }
        }

        private PBArenaInfo m_ArenaInfo;
        [ProtoMember(20, Name = @"ArenaInfo", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBArenaInfo ArenaInfo
        {
            get { return m_ArenaInfo; }
            set { m_ArenaInfo = value; }
        }

        private PBInstanceForCoinResourceInfo m_InstanceForCoinResource;
        [ProtoMember(21, Name = @"InstanceForCoinResource", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBInstanceForCoinResourceInfo InstanceForCoinResource
        {
            get { return m_InstanceForCoinResource; }
            set { m_InstanceForCoinResource = value; }
        }

        private PBInstanceForExpResourceInfo m_InstanceForExpResource;
        [ProtoMember(22, Name = @"InstanceForExpResource", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBInstanceForExpResourceInfo InstanceForExpResource
        {
            get { return m_InstanceForExpResource; }
            set { m_InstanceForExpResource = value; }
        }

        private readonly List<int> m_FuntionId = new List<int>();
        [ProtoMember(23, Name = @"FuntionId", DataFormat = DataFormat.TwosComplement)]
        public List<int> FuntionId
        {
            get { return m_FuntionId; }
        }

        private PBInstanceForTowerInfo m_InstanceForTowerInfo;
        [ProtoMember(24, Name = @"InstanceForTowerInfo", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBInstanceForTowerInfo InstanceForTowerInfo
        {
            get { return m_InstanceForTowerInfo; }
            set { m_InstanceForTowerInfo = value; }
        }

        private readonly List<PBInstanceForBossGroupChestStatus> m_InstanceForBossGroupChestStatus = new List<PBInstanceForBossGroupChestStatus>();
        [ProtoMember(25, Name = @"InstanceForBossGroupChestStatus", DataFormat = DataFormat.Default)]
        public List<PBInstanceForBossGroupChestStatus> InstanceForBossGroupChestStatus
        {
            get { return m_InstanceForBossGroupChestStatus; }
        }

        private readonly List<PBInstanceForGroupBossJoinCountsInfo> m_InstanceForGroupBossJoinCountsInfo = new List<PBInstanceForGroupBossJoinCountsInfo>();
        [ProtoMember(26, Name = @"InstanceForGroupBossJoinCountsInfo", DataFormat = DataFormat.Default)]
        public List<PBInstanceForGroupBossJoinCountsInfo> InstanceForGroupBossJoinCountsInfo
        {
            get { return m_InstanceForGroupBossJoinCountsInfo; }
        }

        private readonly List<PBInstanceForGroupBossProgressInfo> m_InstanceForGroupBossProgressInfo = new List<PBInstanceForGroupBossProgressInfo>();
        [ProtoMember(27, Name = @"InstanceForGroupBossProgressInfo", DataFormat = DataFormat.Default)]
        public List<PBInstanceForGroupBossProgressInfo> InstanceForGroupBossProgressInfo
        {
            get { return m_InstanceForGroupBossProgressInfo; }
        }

        private PBOnlineRewardInfo m_OnlineRewardInfo;
        [ProtoMember(28, Name = @"OnlineRewardInfo", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBOnlineRewardInfo OnlineRewardInfo
        {
            get { return m_OnlineRewardInfo; }
            set { m_OnlineRewardInfo = value; }
        }

        private PBSevenDayLoginInfo m_SevenDayLoginInfo;
        [ProtoMember(29, Name = @"SevenDayLoginInfo", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBSevenDayLoginInfo SevenDayLoginInfo
        {
            get { return m_SevenDayLoginInfo; }
            set { m_SevenDayLoginInfo = value; }
        }

        private readonly List<PBChargeInfo> m_ChargeInfo = new List<PBChargeInfo>();
        [ProtoMember(30, Name = @"ChargeInfo", DataFormat = DataFormat.Default)]
        public List<PBChargeInfo> ChargeInfo
        {
            get { return m_ChargeInfo; }
        }
    }
}
