//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 1402_LCSynthesizeHeroQualityItem.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"LCSynthesizeHeroQualityItem")]
    public partial class LCSynthesizeHeroQualityItem : PacketBase
    {
        public LCSynthesizeHeroQualityItem() { }

        public override PacketType PacketType { get { return PacketType.LobbyServerToClient; } }

        public override int PacketActionId { get { return 1402; } }

        private readonly List<PBItemInfo> m_HeroQualityItemInfos = new List<PBItemInfo>();
        [ProtoMember(1, Name = @"HeroQualityItemInfos", DataFormat = DataFormat.Default)]
        public List<PBItemInfo> HeroQualityItemInfos
        {
            get { return m_HeroQualityItemInfos; }
        }

        private PBPlayerInfo m_PlayerInfo = null;
        [ProtoMember(2, Name = @"PlayerInfo", IsRequired = false, DataFormat = DataFormat.Default)]
        [System.ComponentModel.DefaultValue(null)]
        public PBPlayerInfo PlayerInfo
        {
            get { return m_PlayerInfo; }
            set { m_PlayerInfo = value; }
        }
    }
}
