//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 1051_LCUpdateAchievement.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"LCUpdateAchievement")]
    public partial class LCUpdateAchievement : PacketBase
    {
        public LCUpdateAchievement() { }

        public override PacketType PacketType { get { return PacketType.LobbyServerToClient; } }

        public override int PacketActionId { get { return 1051; } }

        private readonly List<PBAchievementInfo> m_AchievementInfo = new List<PBAchievementInfo>();
        [ProtoMember(1, Name = @"AchievementInfo", DataFormat = DataFormat.Default)]
        public List<PBAchievementInfo> AchievementInfo
        {
            get { return m_AchievementInfo; }
        }
    }
}
