//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 1061_LCUpdateDailyQuest.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"LCUpdateDailyQuest")]
    public partial class LCUpdateDailyQuest : PacketBase
    {
        public LCUpdateDailyQuest() { }

        public override PacketType PacketType { get { return PacketType.LobbyServerToClient; } }

        public override int PacketActionId { get { return 1061; } }

        private readonly List<PBDailyQuestInfo> m_DailyQuestInfo = new List<PBDailyQuestInfo>();
        [ProtoMember(1, Name = @"DailyQuestInfo", DataFormat = DataFormat.Default)]
        public List<PBDailyQuestInfo> DailyQuestInfo
        {
            get { return m_DailyQuestInfo; }
        }
    }
}
