//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: PBArenaReportInfo.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"PBArenaReportInfo")]
    public partial class PBArenaReportInfo
    {
        public PBArenaReportInfo() { }

        private int m_Result;
        [ProtoMember(1, Name = @"Result", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int Result
        {
            get { return m_Result; }
            set { m_Result = value; }
        }

        private int m_DeltaRank;
        [ProtoMember(2, Name = @"DeltaRank", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int DeltaRank
        {
            get { return m_DeltaRank; }
            set { m_DeltaRank = value; }
        }

        private PBInt64 m_Time;
        [ProtoMember(3, Name = @"Time", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBInt64 Time
        {
            get { return m_Time; }
            set { m_Time = value; }
        }

        private int m_MyMight;
        [ProtoMember(4, Name = @"MyMight", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int MyMight
        {
            get { return m_MyMight; }
            set { m_MyMight = value; }
        }

        private PBPlayerInfo m_ArenaPlayerInfo;
        [ProtoMember(5, Name = @"ArenaPlayerInfo", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBPlayerInfo ArenaPlayerInfo
        {
            get { return m_ArenaPlayerInfo; }
            set { m_ArenaPlayerInfo = value; }
        }
    }
}
