//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: PBDailyQuestActivenessInfo.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"PBDailyQuestActivenessInfo")]
    public partial class PBDailyQuestActivenessInfo
    {
        public PBDailyQuestActivenessInfo() { }

        private int m_ClaimRewardStatus;
        [ProtoMember(1, Name = @"ClaimRewardStatus", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int ClaimRewardStatus
        {
            get { return m_ClaimRewardStatus; }
            set { m_ClaimRewardStatus = value; }
        }
    }
}
