//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: PBFriendEnergy.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"PBFriendEnergy")]
    public partial class PBFriendEnergy
    {
        public PBFriendEnergy() { }

        private int m_TodayGiveCount;
        [ProtoMember(1, Name = @"TodayGiveCount", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int TodayGiveCount
        {
            get { return m_TodayGiveCount; }
            set { m_TodayGiveCount = value; }
        }

        private int m_TodayClaimCount;
        [ProtoMember(2, Name = @"TodayClaimCount", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int TodayClaimCount
        {
            get { return m_TodayClaimCount; }
            set { m_TodayClaimCount = value; }
        }
    }
}
