//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: PBHeroSkillBadgesInfo.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"PBHeroSkillBadgesInfo")]
    public partial class PBHeroSkillBadgesInfo
    {
        public PBHeroSkillBadgesInfo() { }

        private int? m_SpecificBadgeId;
        [ProtoMember(1, Name = @"SpecificBadgeId", IsRequired = false, DataFormat = DataFormat.TwosComplement)]
        public int SpecificBadgeId
        {
            get { return m_SpecificBadgeId ?? default(int); }
            set { m_SpecificBadgeId = value; }
        }
        public bool HasSpecificBadgeId { get { return m_SpecificBadgeId != null; } }
        private void ResetSpecificBadgeId() { m_SpecificBadgeId = null; }
        private bool ShouldSerializeSpecificBadgeId() { return HasSpecificBadgeId; }

        private bool m_HasGenericBadgeIds;
        [ProtoMember(2, Name = @"HasGenericBadgeIds", IsRequired = true, DataFormat = DataFormat.Default)]
        public bool HasGenericBadgeIds
        {
            get { return m_HasGenericBadgeIds; }
            set { m_HasGenericBadgeIds = value; }
        }

        private readonly List<int> m_GenericBadgeIds = new List<int>();
        [ProtoMember(3, Name = @"GenericBadgeIds", DataFormat = DataFormat.TwosComplement)]
        public List<int> GenericBadgeIds
        {
            get { return m_GenericBadgeIds; }
        }
    }
}
