//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: PBHeroTeamInfo.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"PBHeroTeamInfo")]
    public partial class PBHeroTeamInfo
    {
        public PBHeroTeamInfo() { }

        private int m_Type;
        [ProtoMember(1, Name = @"Type", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int Type
        {
            get { return m_Type; }
            set { m_Type = value; }
        }

        private readonly List<int> m_HeroType = new List<int>();
        [ProtoMember(2, Name = @"HeroType", DataFormat = DataFormat.TwosComplement)]
        public List<int> HeroType
        {
            get { return m_HeroType; }
        }
    }
}
