//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: PBInstanceForExpResourceInfo.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"PBInstanceForExpResourceInfo")]
    public partial class PBInstanceForExpResourceInfo
    {
        public PBInstanceForExpResourceInfo() { }

        private int m_PlayedCount;
        [ProtoMember(1, Name = @"PlayedCount", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int PlayedCount
        {
            get { return m_PlayedCount; }
            set { m_PlayedCount = value; }
        }
    }
}
