//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: PBInstanceForGroupBossJoinCountsInfo.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"PBInstanceForGroupBossJoinCountsInfo")]
    public partial class PBInstanceForGroupBossJoinCountsInfo
    {
        public PBInstanceForGroupBossJoinCountsInfo() { }

        private int m_Id;
        [ProtoMember(1, Name = @"Id", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int Id
        {
            get { return m_Id; }
            set { m_Id = value; }
        }

        private int m_Count;
        [ProtoMember(2, Name = @"Count", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int Count
        {
            get { return m_Count; }
            set { m_Count = value; }
        }
    }
}
