//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: PBMeridianInfo.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"PBMeridianInfo")]
    public partial class PBMeridianInfo
    {
        public PBMeridianInfo() { }

        private int m_MeridianProgress;
        [ProtoMember(1, Name = @"MeridianProgress", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int MeridianProgress
        {
            get { return m_MeridianProgress; }
            set { m_MeridianProgress = value; }
        }
    }
}
