//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: PBNearbyPlayerInfo.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"PBNearbyPlayerInfo")]
    public partial class PBNearbyPlayerInfo
    {
        public PBNearbyPlayerInfo() { }

        private PBPlayerInfo m_PlayerInfo;
        [ProtoMember(1, Name = @"PlayerInfo", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBPlayerInfo PlayerInfo
        {
            get { return m_PlayerInfo; }
            set { m_PlayerInfo = value; }
        }

        private int m_MainHeroType;
        [ProtoMember(2, Name = @"MainHeroType", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int MainHeroType
        {
            get { return m_MainHeroType; }
            set { m_MainHeroType = value; }
        }
    }
}
