//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: PBNewGearInfo.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"PBNewGearInfo")]
    public partial class PBNewGearInfo
    {
        public PBNewGearInfo() { }

        private int m_TypeId;
        [ProtoMember(1, Name = @"TypeId", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int TypeId
        {
            get { return m_TypeId; }
            set { m_TypeId = value; }
        }

        private int? m_StrengthenLevel;
        [ProtoMember(2, Name = @"StrengthenLevel", IsRequired = false, DataFormat = DataFormat.TwosComplement)]
        public int StrengthenLevel
        {
            get { return m_StrengthenLevel ?? default(int); }
            set { m_StrengthenLevel = value; }
        }
        public bool HasStrengthenLevel { get { return m_StrengthenLevel != null; } }
        private void ResetStrengthenLevel() { m_StrengthenLevel = null; }
        private bool ShouldSerializeStrengthenLevel() { return HasStrengthenLevel; }

        private int? m_TotalQualityLevel;
        [ProtoMember(3, Name = @"TotalQualityLevel", IsRequired = false, DataFormat = DataFormat.TwosComplement)]
        public int TotalQualityLevel
        {
            get { return m_TotalQualityLevel ?? default(int); }
            set { m_TotalQualityLevel = value; }
        }
        public bool HasTotalQualityLevel { get { return m_TotalQualityLevel != null; } }
        private void ResetTotalQualityLevel() { m_TotalQualityLevel = null; }
        private bool ShouldSerializeTotalQualityLevel() { return HasTotalQualityLevel; }
    }
}
