//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: PBPlayerDetail.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"PBPlayerDetail")]
    public partial class PBPlayerDetail
    {
        public PBPlayerDetail() { }

        private PBPlayerInfo m_PlayerInfo;
        [ProtoMember(1, Name = @"PlayerInfo", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBPlayerInfo PlayerInfo
        {
            get { return m_PlayerInfo; }
            set { m_PlayerInfo = value; }
        }

        private readonly List<PBLobbyHeroInfo> m_HeroInfo = new List<PBLobbyHeroInfo>();
        [ProtoMember(2, Name = @"HeroInfo", DataFormat = DataFormat.Default)]
        public List<PBLobbyHeroInfo> HeroInfo
        {
            get { return m_HeroInfo; }
        }

        private PBHeroTeamInfo m_HeroTeamInfo;
        [ProtoMember(3, Name = @"HeroTeamInfo", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBHeroTeamInfo HeroTeamInfo
        {
            get { return m_HeroTeamInfo; }
            set { m_HeroTeamInfo = value; }
        }
    }
}
