//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: PBPlayerPvpInfo.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"PBPlayerPvpInfo")]
    public partial class PBPlayerPvpInfo
    {
        public PBPlayerPvpInfo() { }

        private string m_RoomHost;
        [ProtoMember(1, Name = @"RoomHost", IsRequired = true, DataFormat = DataFormat.Default)]
        public string RoomHost
        {
            get { return m_RoomHost; }
            set { m_RoomHost = value; }
        }

        private int m_RoomPort;
        [ProtoMember(2, Name = @"RoomPort", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int RoomPort
        {
            get { return m_RoomPort; }
            set { m_RoomPort = value; }
        }

        private int m_RoomId;
        [ProtoMember(3, Name = @"RoomId", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int RoomId
        {
            get { return m_RoomId; }
            set { m_RoomId = value; }
        }

        private string m_Token;
        [ProtoMember(4, Name = @"Token", IsRequired = true, DataFormat = DataFormat.Default)]
        public string Token
        {
            get { return m_Token; }
            set { m_Token = value; }
        }

        private int m_InstanceId;
        [ProtoMember(5, Name = @"InstanceId", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int InstanceId
        {
            get { return m_InstanceId; }
            set { m_InstanceId = value; }
        }
    }
}
