//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: PBPlayerInfo.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"PBPlayerInfo")]
    public partial class PBPlayerInfo
    {
        public PBPlayerInfo() { }

        private int m_Id;
        [ProtoMember(1, Name = @"Id", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int Id
        {
            get { return m_Id; }
            set { m_Id = value; }
        }

        private string m_Name;
        [ProtoMember(2, Name = @"Name", IsRequired = false, DataFormat = DataFormat.Default)]
        public string Name
        {
            get { return m_Name ?? ""; }
            set { m_Name = value; }
        }
        public bool HasName { get { return m_Name != null; } }
        private void ResetName() { m_Name = null; }
        private bool ShouldSerializeName() { return HasName; }

        private bool? m_IsFemale;
        [ProtoMember(3, Name = @"IsFemale", IsRequired = false, DataFormat = DataFormat.Default)]
        public bool IsFemale
        {
            get { return m_IsFemale ?? default(bool); }
            set { m_IsFemale = value; }
        }
        public bool HasIsFemale { get { return m_IsFemale != null; } }
        private void ResetIsFemale() { m_IsFemale = null; }
        private bool ShouldSerializeIsFemale() { return HasIsFemale; }

        private int? m_PortraitType;
        [ProtoMember(4, Name = @"PortraitType", IsRequired = false, DataFormat = DataFormat.TwosComplement)]
        public int PortraitType
        {
            get { return m_PortraitType ?? default(int); }
            set { m_PortraitType = value; }
        }
        public bool HasPortraitType { get { return m_PortraitType != null; } }
        private void ResetPortraitType() { m_PortraitType = null; }
        private bool ShouldSerializePortraitType() { return HasPortraitType; }

        private int? m_Level;
        [ProtoMember(5, Name = @"Level", IsRequired = false, DataFormat = DataFormat.TwosComplement)]
        public int Level
        {
            get { return m_Level ?? default(int); }
            set { m_Level = value; }
        }
        public bool HasLevel { get { return m_Level != null; } }
        private void ResetLevel() { m_Level = null; }
        private bool ShouldSerializeLevel() { return HasLevel; }

        private int? m_Exp;
        [ProtoMember(6, Name = @"Exp", IsRequired = false, DataFormat = DataFormat.TwosComplement)]
        public int Exp
        {
            get { return m_Exp ?? default(int); }
            set { m_Exp = value; }
        }
        public bool HasExp { get { return m_Exp != null; } }
        private void ResetExp() { m_Exp = null; }
        private bool ShouldSerializeExp() { return HasExp; }

        private int? m_Money;
        [ProtoMember(7, Name = @"Money", IsRequired = false, DataFormat = DataFormat.TwosComplement)]
        public int Money
        {
            get { return m_Money ?? default(int); }
            set { m_Money = value; }
        }
        public bool HasMoney { get { return m_Money != null; } }
        private void ResetMoney() { m_Money = null; }
        private bool ShouldSerializeMoney() { return HasMoney; }

        private int? m_Coin;
        [ProtoMember(8, Name = @"Coin", IsRequired = false, DataFormat = DataFormat.TwosComplement)]
        public int Coin
        {
            get { return m_Coin ?? default(int); }
            set { m_Coin = value; }
        }
        public bool HasCoin { get { return m_Coin != null; } }
        private void ResetCoin() { m_Coin = null; }
        private bool ShouldSerializeCoin() { return HasCoin; }

        private int? m_Energy;
        [ProtoMember(9, Name = @"Energy", IsRequired = false, DataFormat = DataFormat.TwosComplement)]
        public int Energy
        {
            get { return m_Energy ?? default(int); }
            set { m_Energy = value; }
        }
        public bool HasEnergy { get { return m_Energy != null; } }
        private void ResetEnergy() { m_Energy = null; }
        private bool ShouldSerializeEnergy() { return HasEnergy; }

        private int? m_VipLevel;
        [ProtoMember(11, Name = @"VipLevel", IsRequired = false, DataFormat = DataFormat.TwosComplement)]
        public int VipLevel
        {
            get { return m_VipLevel ?? default(int); }
            set { m_VipLevel = value; }
        }
        public bool HasVipLevel { get { return m_VipLevel != null; } }
        private void ResetVipLevel() { m_VipLevel = null; }
        private bool ShouldSerializeVipLevel() { return HasVipLevel; }

        private int? m_VipExp;
        [ProtoMember(12, Name = @"VipExp", IsRequired = false, DataFormat = DataFormat.TwosComplement)]
        public int VipExp
        {
            get { return m_VipExp ?? default(int); }
            set { m_VipExp = value; }
        }
        public bool HasVipExp { get { return m_VipExp != null; } }
        private void ResetVipExp() { m_VipExp = null; }
        private bool ShouldSerializeVipExp() { return HasVipExp; }

        private int? m_Spirit;
        [ProtoMember(13, Name = @"Spirit", IsRequired = false, DataFormat = DataFormat.TwosComplement)]
        public int Spirit
        {
            get { return m_Spirit ?? default(int); }
            set { m_Spirit = value; }
        }
        public bool HasSpirit { get { return m_Spirit != null; } }
        private void ResetSpirit() { m_Spirit = null; }
        private bool ShouldSerializeSpirit() { return HasSpirit; }

        private int? m_MeridianEnergy;
        [ProtoMember(14, Name = @"MeridianEnergy", IsRequired = false, DataFormat = DataFormat.TwosComplement)]
        public int MeridianEnergy
        {
            get { return m_MeridianEnergy ?? default(int); }
            set { m_MeridianEnergy = value; }
        }
        public bool HasMeridianEnergy { get { return m_MeridianEnergy != null; } }
        private void ResetMeridianEnergy() { m_MeridianEnergy = null; }
        private bool ShouldSerializeMeridianEnergy() { return HasMeridianEnergy; }

        private int? m_ArenaToken;
        [ProtoMember(15, Name = @"ArenaToken", IsRequired = false, DataFormat = DataFormat.TwosComplement)]
        public int ArenaToken
        {
            get { return m_ArenaToken ?? default(int); }
            set { m_ArenaToken = value; }
        }
        public bool HasArenaToken { get { return m_ArenaToken != null; } }
        private void ResetArenaToken() { m_ArenaToken = null; }
        private bool ShouldSerializeArenaToken() { return HasArenaToken; }

        private int? m_PvpToken;
        [ProtoMember(16, Name = @"PvpToken", IsRequired = false, DataFormat = DataFormat.TwosComplement)]
        public int PvpToken
        {
            get { return m_PvpToken ?? default(int); }
            set { m_PvpToken = value; }
        }
        public bool HasPvpToken { get { return m_PvpToken != null; } }
        private void ResetPvpToken() { m_PvpToken = null; }
        private bool ShouldSerializePvpToken() { return HasPvpToken; }

        private int? m_DragonStripeToken;
        [ProtoMember(17, Name = @"DragonStripeToken", IsRequired = false, DataFormat = DataFormat.TwosComplement)]
        public int DragonStripeToken
        {
            get { return m_DragonStripeToken ?? default(int); }
            set { m_DragonStripeToken = value; }
        }
        public bool HasDragonStripeToken { get { return m_DragonStripeToken != null; } }
        private void ResetDragonStripeToken() { m_DragonStripeToken = null; }
        private bool ShouldSerializeDragonStripeToken() { return HasDragonStripeToken; }

        private int? m_DisplayId;
        [ProtoMember(18, Name = @"DisplayId", IsRequired = false, DataFormat = DataFormat.TwosComplement)]
        public int DisplayId
        {
            get { return m_DisplayId ?? default(int); }
            set { m_DisplayId = value; }
        }
        public bool HasDisplayId { get { return m_DisplayId != null; } }
        private void ResetDisplayId() { m_DisplayId = null; }
        private bool ShouldSerializeDisplayId() { return HasDisplayId; }

        private int? m_PlayerHeroCount;
        [ProtoMember(19, Name = @"PlayerHeroCount", IsRequired = false, DataFormat = DataFormat.TwosComplement)]
        public int PlayerHeroCount
        {
            get { return m_PlayerHeroCount ?? default(int); }
            set { m_PlayerHeroCount = value; }
        }
        public bool HasPlayerHeroCount { get { return m_PlayerHeroCount != null; } }
        private void ResetPlayerHeroCount() { m_PlayerHeroCount = null; }
        private bool ShouldSerializePlayerHeroCount() { return HasPlayerHeroCount; }

        private PBInt64 m_NextEnergyRecoveryTime = null;
        [ProtoMember(20, Name = @"NextEnergyRecoveryTime", IsRequired = false, DataFormat = DataFormat.Default)]
        [System.ComponentModel.DefaultValue(null)]
        public PBInt64 NextEnergyRecoveryTime
        {
            get { return m_NextEnergyRecoveryTime; }
            set { m_NextEnergyRecoveryTime = value; }
        }

        private int? m_Might;
        [ProtoMember(21, Name = @"Might", IsRequired = false, DataFormat = DataFormat.TwosComplement)]
        public int Might
        {
            get { return m_Might ?? default(int); }
            set { m_Might = value; }
        }
        public bool HasMight { get { return m_Might != null; } }
        private void ResetMight() { m_Might = null; }
        private bool ShouldSerializeMight() { return HasMight; }

        private bool? m_IsOnline;
        [ProtoMember(22, Name = @"IsOnline", IsRequired = false, DataFormat = DataFormat.Default)]
        public bool IsOnline
        {
            get { return m_IsOnline ?? default(bool); }
            set { m_IsOnline = value; }
        }
        public bool HasIsOnline { get { return m_IsOnline != null; } }
        private void ResetIsOnline() { m_IsOnline = null; }
        private bool ShouldSerializeIsOnline() { return HasIsOnline; }

        private PBVector2 m_Position = null;
        [ProtoMember(23, Name = @"Position", IsRequired = false, DataFormat = DataFormat.Default)]
        [System.ComponentModel.DefaultValue(null)]
        public PBVector2 Position
        {
            get { return m_Position; }
            set { m_Position = value; }
        }

        private int? m_ActivenessToken;
        [ProtoMember(24, Name = @"ActivenessToken", IsRequired = false, DataFormat = DataFormat.TwosComplement)]
        public int ActivenessToken
        {
            get { return m_ActivenessToken ?? default(int); }
            set { m_ActivenessToken = value; }
        }
        public bool HasActivenessToken { get { return m_ActivenessToken != null; } }
        private void ResetActivenessToken() { m_ActivenessToken = null; }
        private bool ShouldSerializeActivenessToken() { return HasActivenessToken; }

        private int? m_GuidanceGroupId;
        [ProtoMember(25, Name = @"GuidanceGroupId", IsRequired = false, DataFormat = DataFormat.TwosComplement)]
        public int GuidanceGroupId
        {
            get { return m_GuidanceGroupId ?? default(int); }
            set { m_GuidanceGroupId = value; }
        }
        public bool HasGuidanceGroupId { get { return m_GuidanceGroupId != null; } }
        private void ResetGuidanceGroupId() { m_GuidanceGroupId = null; }
        private bool ShouldSerializeGuidanceGroupId() { return HasGuidanceGroupId; }
    }
}
