//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: PBPVPSettlement.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"PBPVPSettlement")]
    public partial class PBPVPSettlement
    {
        public PBPVPSettlement() { }

        private int m_UserId;
        [ProtoMember(1, Name = @"UserId", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int UserId
        {
            get { return m_UserId; }
            set { m_UserId = value; }
        }

        private int m_OldRank;
        [ProtoMember(2, Name = @"OldRank", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int OldRank
        {
            get { return m_OldRank; }
            set { m_OldRank = value; }
        }

        private int m_Rank;
        [ProtoMember(3, Name = @"Rank", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int Rank
        {
            get { return m_Rank; }
            set { m_Rank = value; }
        }

        private int m_OldScore;
        [ProtoMember(4, Name = @"OldScore", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int OldScore
        {
            get { return m_OldScore; }
            set { m_OldScore = value; }
        }

        private int m_Score;
        [ProtoMember(5, Name = @"Score", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int Score
        {
            get { return m_Score; }
            set { m_Score = value; }
        }

        private int m_Coin;
        [ProtoMember(6, Name = @"Coin", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int Coin
        {
            get { return m_Coin; }
            set { m_Coin = value; }
        }

        private int m_Gold;
        [ProtoMember(7, Name = @"Gold", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int Gold
        {
            get { return m_Gold; }
            set { m_Gold = value; }
        }

        private readonly List<int> m_Damages = new List<int>();
        [ProtoMember(8, Name = @"Damages", DataFormat = DataFormat.TwosComplement)]
        public List<int> Damages
        {
            get { return m_Damages; }
        }

        private readonly List<int> m_KillCounts = new List<int>();
        [ProtoMember(9, Name = @"KillCounts", DataFormat = DataFormat.TwosComplement)]
        public List<int> KillCounts
        {
            get { return m_KillCounts; }
        }

        private readonly List<bool> m_DeadState = new List<bool>();
        [ProtoMember(10, Name = @"DeadState", DataFormat = DataFormat.Default)]
        public List<bool> DeadState
        {
            get { return m_DeadState; }
        }
    }
}
