//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: PBRankInfo.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"PBRankInfo")]
    public partial class PBRankInfo
    {
        public PBRankInfo() { }

        private int m_Ranking;
        [ProtoMember(1, Name = @"Ranking", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int Ranking
        {
            get { return m_Ranking; }
            set { m_Ranking = value; }
        }

        private PBPlayerInfo m_PlayerInfo;
        [ProtoMember(2, Name = @"PlayerInfo", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBPlayerInfo PlayerInfo
        {
            get { return m_PlayerInfo; }
            set { m_PlayerInfo = value; }
        }

        private int m_Score;
        [ProtoMember(3, Name = @"Score", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int Score
        {
            get { return m_Score; }
            set { m_Score = value; }
        }

        private PBInt64 m_RankTime;
        [ProtoMember(4, Name = @"RankTime", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBInt64 RankTime
        {
            get { return m_RankTime; }
            set { m_RankTime = value; }
        }

        private int? m_ServerId;
        [ProtoMember(5, Name = @"ServerId", IsRequired = false, DataFormat = DataFormat.TwosComplement)]
        public int ServerId
        {
            get { return m_ServerId ?? default(int); }
            set { m_ServerId = value; }
        }
        public bool HasServerId { get { return m_ServerId != null; } }
        private void ResetServerId() { m_ServerId = null; }
        private bool ShouldSerializeServerId() { return HasServerId; }

        private readonly List<int> m_ArenaHeroTypes = new List<int>();
        [ProtoMember(6, Name = @"ArenaHeroTypes", DataFormat = DataFormat.TwosComplement)]
        public List<int> ArenaHeroTypes
        {
            get { return m_ArenaHeroTypes; }
        }

        private int? m_ArenaMight;
        [ProtoMember(7, Name = @"ArenaMight", IsRequired = false, DataFormat = DataFormat.TwosComplement)]
        public int ArenaMight
        {
            get { return m_ArenaMight ?? default(int); }
            set { m_ArenaMight = value; }
        }
        public bool HasArenaMight { get { return m_ArenaMight != null; } }
        private void ResetArenaMight() { m_ArenaMight = null; }
        private bool ShouldSerializeArenaMight() { return HasArenaMight; }
    }
}
