//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: PBShopItem.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"PBShopItem")]
    public partial class PBShopItem
    {
        public PBShopItem() { }

        private PBItemInfo m_ItemInfo;
        [ProtoMember(1, Name = @"ItemInfo", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBItemInfo ItemInfo
        {
            get { return m_ItemInfo; }
            set { m_ItemInfo = value; }
        }

        private PBCurrencyInfo m_CurrencyInfo;
        [ProtoMember(2, Name = @"CurrencyInfo", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBCurrencyInfo CurrencyInfo
        {
            get { return m_CurrencyInfo; }
            set { m_CurrencyInfo = value; }
        }

        private bool m_CanBuy;
        [ProtoMember(5, Name = @"CanBuy", IsRequired = true, DataFormat = DataFormat.Default)]
        public bool CanBuy
        {
            get { return m_CanBuy; }
            set { m_CanBuy = value; }
        }
    }
}
