//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: PBTaskInfo.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"PBTaskInfo")]
    public partial class PBTaskInfo
    {
        public PBTaskInfo() { }

        private int m_TaskId;
        [ProtoMember(1, Name = @"TaskId", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int TaskId
        {
            get { return m_TaskId; }
            set { m_TaskId = value; }
        }

        private int? m_conditon1;
        [ProtoMember(2, Name = @"conditon1", IsRequired = false, DataFormat = DataFormat.TwosComplement)]
        public int conditon1
        {
            get { return m_conditon1 ?? default(int); }
            set { m_conditon1 = value; }
        }
        public bool Hasconditon1 { get { return m_conditon1 != null; } }
        private void Resetconditon1() { m_conditon1 = null; }
        private bool ShouldSerializeconditon1() { return Hasconditon1; }

        private int? m_conditon2;
        [ProtoMember(3, Name = @"conditon2", IsRequired = false, DataFormat = DataFormat.TwosComplement)]
        public int conditon2
        {
            get { return m_conditon2 ?? default(int); }
            set { m_conditon2 = value; }
        }
        public bool Hasconditon2 { get { return m_conditon2 != null; } }
        private void Resetconditon2() { m_conditon2 = null; }
        private bool ShouldSerializeconditon2() { return Hasconditon2; }

        private int? m_conditon3;
        [ProtoMember(4, Name = @"conditon3", IsRequired = false, DataFormat = DataFormat.TwosComplement)]
        public int conditon3
        {
            get { return m_conditon3 ?? default(int); }
            set { m_conditon3 = value; }
        }
        public bool Hasconditon3 { get { return m_conditon3 != null; } }
        private void Resetconditon3() { m_conditon3 = null; }
        private bool ShouldSerializeconditon3() { return Hasconditon3; }

        private int? m_conditon4;
        [ProtoMember(5, Name = @"conditon4", IsRequired = false, DataFormat = DataFormat.TwosComplement)]
        public int conditon4
        {
            get { return m_conditon4 ?? default(int); }
            set { m_conditon4 = value; }
        }
        public bool Hasconditon4 { get { return m_conditon4 != null; } }
        private void Resetconditon4() { m_conditon4 = null; }
        private bool ShouldSerializeconditon4() { return Hasconditon4; }

        private PBInt64 m_ClaimRewardTime = null;
        [ProtoMember(6, Name = @"ClaimRewardTime", IsRequired = false, DataFormat = DataFormat.Default)]
        [System.ComponentModel.DefaultValue(null)]
        public PBInt64 ClaimRewardTime
        {
            get { return m_ClaimRewardTime; }
            set { m_ClaimRewardTime = value; }
        }

        private PBInt64 m_LastUpdateTime = null;
        [ProtoMember(7, Name = @"LastUpdateTime", IsRequired = false, DataFormat = DataFormat.Default)]
        [System.ComponentModel.DefaultValue(null)]
        public PBInt64 LastUpdateTime
        {
            get { return m_LastUpdateTime; }
            set { m_LastUpdateTime = value; }
        }
    }
}
