//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: PBVipPrivilegeInfo.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"PBVipPrivilegeInfo")]
    public partial class PBVipPrivilegeInfo
    {
        public PBVipPrivilegeInfo() { }

        private int m_VipPrivilegeType;
        [ProtoMember(1, Name = @"VipPrivilegeType", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int VipPrivilegeType
        {
            get { return m_VipPrivilegeType; }
            set { m_VipPrivilegeType = value; }
        }

        private int m_UsedVipPrivilegeCount;
        [ProtoMember(2, Name = @"UsedVipPrivilegeCount", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int UsedVipPrivilegeCount
        {
            get { return m_UsedVipPrivilegeCount; }
            set { m_UsedVipPrivilegeCount = value; }
        }
    }
}
