//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 5011_RCEndSinglePVP.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"RCEndSinglePVP")]
    public partial class RCEndSinglePVP : PacketBase
    {
        public RCEndSinglePVP() { }

        public override PacketType PacketType { get { return PacketType.RoomServerToClient; } }

        public override int PacketActionId { get { return 5011; } }

        private int m_Winner;
        [ProtoMember(1, Name = @"Winner", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int Winner
        {
            get { return m_Winner; }
            set { m_Winner = value; }
        }

        private string m_WinnerName;
        [ProtoMember(2, Name = @"WinnerName", IsRequired = true, DataFormat = DataFormat.Default)]
        public string WinnerName
        {
            get { return m_WinnerName; }
            set { m_WinnerName = value; }
        }

        private string m_WinnerServerName;
        [ProtoMember(3, Name = @"WinnerServerName", IsRequired = true, DataFormat = DataFormat.Default)]
        public string WinnerServerName
        {
            get { return m_WinnerServerName; }
            set { m_WinnerServerName = value; }
        }

        private int m_Reason;
        [ProtoMember(4, Name = @"Reason", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int Reason
        {
            get { return m_Reason; }
            set { m_Reason = value; }
        }

        private readonly List<PBPVPSettlement> m_Settlements = new List<PBPVPSettlement>();
        [ProtoMember(5, Name = @"Settlements", DataFormat = DataFormat.Default)]
        public List<PBPVPSettlement> Settlements
        {
            get { return m_Settlements; }
        }
    }
}
