//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 5014_RCGetRoomBattleStatus.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"RCGetRoomBattleStatus")]
    public partial class RCGetRoomBattleStatus : PacketBase
    {
        public RCGetRoomBattleStatus() { }

        public override PacketType PacketType { get { return PacketType.RoomServerToClient; } }

        public override int PacketActionId { get { return 5014; } }

        private int m_OppCurCharacterIndex;
        [ProtoMember(1, Name = @"OppCurCharacterIndex", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int OppCurCharacterIndex
        {
            get { return m_OppCurCharacterIndex; }
            set { m_OppCurCharacterIndex = value; }
        }

        private int m_MeCurCharacterIndex;
        [ProtoMember(2, Name = @"MeCurCharacterIndex", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int MeCurCharacterIndex
        {
            get { return m_MeCurCharacterIndex; }
            set { m_MeCurCharacterIndex = value; }
        }

        private int m_LeftTime;
        [ProtoMember(3, Name = @"LeftTime", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int LeftTime
        {
            get { return m_LeftTime; }
            set { m_LeftTime = value; }
        }

        private PBTransformInfo m_OppTransform;
        [ProtoMember(4, Name = @"OppTransform", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBTransformInfo OppTransform
        {
            get { return m_OppTransform; }
            set { m_OppTransform = value; }
        }

        private PBTransformInfo m_MeTransform;
        [ProtoMember(5, Name = @"MeTransform", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBTransformInfo MeTransform
        {
            get { return m_MeTransform; }
            set { m_MeTransform = value; }
        }

        private readonly List<PBRoomOnlineCharacterInfo> m_OppCharacterInfos = new List<PBRoomOnlineCharacterInfo>();
        [ProtoMember(6, Name = @"OppCharacterInfos", DataFormat = DataFormat.Default)]
        public List<PBRoomOnlineCharacterInfo> OppCharacterInfos
        {
            get { return m_OppCharacterInfos; }
        }

        private readonly List<PBRoomOnlineCharacterInfo> m_MeCharacterInfo = new List<PBRoomOnlineCharacterInfo>();
        [ProtoMember(7, Name = @"MeCharacterInfo", DataFormat = DataFormat.Default)]
        public List<PBRoomOnlineCharacterInfo> MeCharacterInfo
        {
            get { return m_MeCharacterInfo; }
        }
    }
}
