//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 4016_RCPushPlayerDisconnect.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"RCPushPlayerDisconnect")]
    public partial class RCPushPlayerDisconnect : PacketBase
    {
        public RCPushPlayerDisconnect() { }

        public override PacketType PacketType { get { return PacketType.RoomServerToClient; } }

        public override int PacketActionId { get { return 4016; } }

        private int m_PlayerId;
        [ProtoMember(1, Name = @"PlayerId", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int PlayerId
        {
            get { return m_PlayerId; }
            set { m_PlayerId = value; }
        }

        private bool m_Status;
        [ProtoMember(2, Name = @"Status", IsRequired = true, DataFormat = DataFormat.Default)]
        public bool Status
        {
            get { return m_Status; }
            set { m_Status = value; }
        }
    }
}
