//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 4111_RCPushEntitySteadyChanged.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"RCPushEntitySteadyChanged")]
    public partial class RCPushEntitySteadyChanged : PacketBase
    {
        public RCPushEntitySteadyChanged() { }

        public override PacketType PacketType { get { return PacketType.RoomServerToClient; } }

        public override int PacketActionId { get { return 4111; } }

        private int m_PlayerId;
        [ProtoMember(1, Name = @"PlayerId", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int PlayerId
        {
            get { return m_PlayerId; }
            set { m_PlayerId = value; }
        }

        private int m_TargetPlayerId;
        [ProtoMember(2, Name = @"TargetPlayerId", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int TargetPlayerId
        {
            get { return m_TargetPlayerId; }
            set { m_TargetPlayerId = value; }
        }

        private int m_ChangedEntityId;
        [ProtoMember(3, Name = @"ChangedEntityId", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int ChangedEntityId
        {
            get { return m_ChangedEntityId; }
            set { m_ChangedEntityId = value; }
        }

        private bool m_SteadyStatus;
        [ProtoMember(4, Name = @"SteadyStatus", IsRequired = true, DataFormat = DataFormat.Default)]
        public bool SteadyStatus
        {
            get { return m_SteadyStatus; }
            set { m_SteadyStatus = value; }
        }

        private int m_SteadyValue;
        [ProtoMember(5, Name = @"SteadyValue", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int SteadyValue
        {
            get { return m_SteadyValue; }
            set { m_SteadyValue = value; }
        }
    }
}
