//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 4104_RCPushEntitySwitchHero.proto
//----------------------------------------------------------------------------------------------------

using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    [Serializable, ProtoContract(Name = @"RCPushEntitySwitchHero")]
    public partial class RCPushEntitySwitchHero : PacketBase
    {
        public RCPushEntitySwitchHero() { }

        public override PacketType PacketType { get { return PacketType.RoomServerToClient; } }

        public override int PacketActionId { get { return 4104; } }

        private int m_PlayerId;
        [ProtoMember(1, Name = @"PlayerId", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int PlayerId
        {
            get { return m_PlayerId; }
            set { m_PlayerId = value; }
        }

        private int m_OldEntityId;
        [ProtoMember(2, Name = @"OldEntityId", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int OldEntityId
        {
            get { return m_OldEntityId; }
            set { m_OldEntityId = value; }
        }

        private int m_NewEntityId;
        [ProtoMember(3, Name = @"NewEntityId", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int NewEntityId
        {
            get { return m_NewEntityId; }
            set { m_NewEntityId = value; }
        }

        private int m_HP;
        [ProtoMember(4, Name = @"HP", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int HP
        {
            get { return m_HP; }
            set { m_HP = value; }
        }

        private float? m_SteadyValue;
        [ProtoMember(5, Name = @"SteadyValue", IsRequired = false, DataFormat = DataFormat.FixedSize)]
        public float SteadyValue
        {
            get { return m_SteadyValue ?? default(float); }
            set { m_SteadyValue = value; }
        }
        public bool HasSteadyValue { get { return m_SteadyValue != null; } }
        private void ResetSteadyValue() { m_SteadyValue = null; }
        private bool ShouldSerializeSteadyValue() { return HasSteadyValue; }

        private bool? m_SteadyBarStatus;
        [ProtoMember(6, Name = @"SteadyBarStatus", IsRequired = false, DataFormat = DataFormat.Default)]
        public bool SteadyBarStatus
        {
            get { return m_SteadyBarStatus ?? default(bool); }
            set { m_SteadyBarStatus = value; }
        }
        public bool HasSteadyBarStatus { get { return m_SteadyBarStatus != null; } }
        private void ResetSteadyBarStatus() { m_SteadyBarStatus = null; }
        private bool ShouldSerializeSteadyBarStatus() { return HasSteadyBarStatus; }

        private PBInt64 m_LastBreakSteadyTime = null;
        [ProtoMember(7, Name = @"LastBreakSteadyTime", IsRequired = false, DataFormat = DataFormat.Default)]
        [System.ComponentModel.DefaultValue(null)]
        public PBInt64 LastBreakSteadyTime
        {
            get { return m_LastBreakSteadyTime; }
            set { m_LastBreakSteadyTime = value; }
        }
    }
}
