//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// You may need to modify 'Handle' method.
// Don't modify the rest unless you know what you're doing.
//----------------------------------------------------------------------------------------------------

using GameFramework.Network;

namespace Genesis.GameClient
{
    public class LCActivateSkillBadgeSlotWithMoneyHandler : BasePacketHandler
    {
        public override int OpCode { get { return NetworkHelper.GetOpCode(PacketType.LobbyServerToClient, 1405); } }

        public override void Handle(object sender, Packet packet)
        {
            base.Handle(sender, packet);
            Handle(sender, packet as LCActivateSkillBadgeSlotWithMoney);
            GameEntry.Event.Fire(this, new LobbyHeroDataChangedEventArgs());
            GameEntry.Event.Fire(this, new HeroSkillDataChangedEventArgs(HeroSkillDataChangedEventArgs.SkillChangeType.OpenSlot));
            GameEntry.Event.Fire(this, new PlayerDataChangedEventArgs());
        }

        public static void Handle(object sender, LCActivateSkillBadgeSlotWithMoney response)
        {
            var data = GameEntry.Data.LobbyHeros.GetData(response.HeroInfo.Type);
            if (data != null)
            {
                data.UpdateData(response.HeroInfo);
            }
            else
            {
                GameEntry.Data.LobbyHeros.AddData(response.HeroInfo);
            }
            GameEntry.Data.Player.UpdateData(response.PlayerInfo);
        }
    }
}
