//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// You may need to modify 'Handle' method.
// Don't modify the rest unless you know what you're doing.
//----------------------------------------------------------------------------------------------------

using GameFramework.Network;

namespace Genesis.GameClient
{
    public class LCChangeHeroTeamHandler : BasePacketHandler
    {
        public override int OpCode { get { return NetworkHelper.GetOpCode(PacketType.LobbyServerToClient, 1009); } }

        public override void Handle(object sender, Packet packet)
        {
            base.Handle(sender, packet);
            LCChangeHeroTeam response = packet as LCChangeHeroTeam;
            if (response.PlayerInfo != null)
            {
                GameEntry.Data.Player.UpdateData(response.PlayerInfo);
            }
            
            GameEntry.Event.Fire(this, new PlayerDataChangedEventArgs());

            GameEntry.Data.HeroTeams.GetData(response.HeroTeamInfo.Type).UpdateData(response.HeroTeamInfo);
            GameEntry.Event.Fire(this, new HeroTeamDataChangedEventArgs((HeroTeamType)response.HeroTeamInfo.Type));
            GameEntry.Event.Fire(this, new OfflineArenaDataChangedEventArgs());
        }
    }
}
