//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// You may need to modify 'Handle' method.
// Don't modify the rest unless you know what you're doing.
//----------------------------------------------------------------------------------------------------

using GameFramework.Network;

namespace Genesis.GameClient
{
    public class LCClaimEnergyHandler : BasePacketHandler
    {
        public override int OpCode { get { return NetworkHelper.GetOpCode(PacketType.LobbyServerToClient, 3107); } }

        public override void Handle(object sender, Packet packet)
        {
            base.Handle(sender, packet);
            Handle(sender, packet as LCClaimEnergy);
        }

        public static void Handle(object sender, LCClaimEnergy response)
        {
            GameEntry.Data.Friends.ModifyTodyClaimCount(response.TodayClaimCount);
            GameEntry.Data.Friends.AddOrModifyFriend(response.FriendInfo);
            GameEntry.Data.Player.UpdateData(response.PlayerInfo);

            GameEntry.Event.Fire(sender, new PlayerDataChangedEventArgs());
            GameEntry.Event.Fire(sender, new EnergyReceivedFromFriendEventArgs(response.FriendInfo.PlayerInfo.Id,
                System.Math.Max(GameEntry.ServerConfig.GetInt(Constant.ServerConfig.Friend.DailyEnergyClaimTimes, 10) - response.TodayClaimCount, 0)));
        }
    }
}
