//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// You may need to modify 'Handle' method.
// Don't modify the rest unless you know what you're doing.
//----------------------------------------------------------------------------------------------------

using GameFramework.Network;

namespace Genesis.GameClient
{
    public class LCClaimActivenessChestHandler : BasePacketHandler
    {
        public override int OpCode { get { return NetworkHelper.GetOpCode(PacketType.LobbyServerToClient, 1063); } }

        public override void Handle(object sender, Packet packet)
        {
            base.Handle(sender, packet);
            Handle(sender, packet as LCClaimActivenessChest);
        }

        public static void Handle(object sender, LCClaimActivenessChest response)
        {
            GameEntry.Data.DailyQuests.ClaimActivenessChestStatus = response.DailyQuestActivenessInfo.ClaimRewardStatus;
            var helper = new RewardCollectionHelper();
            helper.AddCompoundItems(response.CompoundItemInfo);
            GameEntry.Event.Fire(sender, new PlayerDataChangedEventArgs());
            GameEntry.Event.Fire(sender, new ItemDataChangedEventArgs());
            GameEntry.Event.Fire(sender, new ClaimActivenessChestEventArgs(helper.ReceiveGoodsData, response.ChestId));
        }
    }
}
