//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// You may need to modify 'Handle' method.
// Don't modify the rest unless you know what you're doing.
//----------------------------------------------------------------------------------------------------

using GameFramework.Network;

namespace Genesis.GameClient
{
    public class LCClaimOnlineRewardHandler : BasePacketHandler
    {
        public override int OpCode { get { return NetworkHelper.GetOpCode(PacketType.LobbyServerToClient, 2701); } }

        public override void Handle(object sender, Packet packet)
        {
            base.Handle(sender, packet);
            Handle(sender, packet as LCClaimOnlineReward);
        }

        public static void Handle(object sender, LCClaimOnlineReward response)
        {
            GameEntry.Data.OnlineRewardsData.UpdataData(response.OnlineRewardInfo);
            GameEntry.Event.Fire(sender, new ClaimOnlineRewardsEventArgs());
        }
    }
}
