//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// You may need to modify 'Handle' method.
// Don't modify the rest unless you know what you're doing.
//----------------------------------------------------------------------------------------------------

using GameFramework.Network;

namespace Genesis.GameClient
{
    public class LCEnterInstanceHandler : BasePacketHandler
    {
        public override int OpCode { get { return NetworkHelper.GetOpCode(PacketType.LobbyServerToClient, 1004); } }

        public override void Handle(object sender, Packet packet)
        {
            base.Handle(sender, packet);
            LCEnterInstance response = packet as LCEnterInstance;
            GameEntry.Data.Player.UpdateData(response.PlayerInfo);

            if (GameEntry.Procedure.CurrentProcedure is ProcedureMain)
            {
                GameEntry.Event.Fire(this, new WillChangeSceneEventArgs(InstanceLogicType.SinglePlayer, response.InstanceType, true));
            }

            GameEntry.Event.Fire(this, new PlayerDataChangedEventArgs());
        }
    }
}
