//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// You may need to modify 'Handle' method.
// Don't modify the rest unless you know what you're doing.
//----------------------------------------------------------------------------------------------------

using GameFramework.Network;

namespace Genesis.GameClient
{
    public class LCGetChessBoardHandler : BasePacketHandler
    {
        public override int OpCode { get { return NetworkHelper.GetOpCode(PacketType.LobbyServerToClient, 2001); } }

        public override void Handle(object sender, Packet packet)
        {
            base.Handle(sender, packet);
            LCGetChessBoard response = packet as LCGetChessBoard;
            GameEntry.Data.ChessBattleMe.UpdateData(response);
            GameEntry.Event.Fire(this, new ChessBoardRefreshSuccessEventArgs(response));
        }
    }
}
