//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// You may need to modify 'Handle' method.
// Don't modify the rest unless you know what you're doing.
//----------------------------------------------------------------------------------------------------

using GameFramework.Network;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    public class LCGetPlayerDetailHandler : BasePacketHandler
    {
        public override int OpCode { get { return NetworkHelper.GetOpCode(PacketType.LobbyServerToClient, 3301); } }

        public override void Handle(object sender, Packet packet)
        {
            base.Handle(sender, packet);
            Handle(sender, packet as LCGetPlayerDetail);
        }

        public static void Handle(object sender, LCGetPlayerDetail response)
        {
            GetPlayerInfoEventArgs playerDetails = new GetPlayerInfoEventArgs();
            PlayerData playerData = new PlayerData();
            playerData.UpdateData(response.PlayerDetail.PlayerInfo);
            playerDetails.PlayerData = playerData;
            List<LobbyHeroData> heros = new List<LobbyHeroData>();
            for (int i = 0; i < response.PlayerDetail.HeroInfo.Count; i++)
            {
                LobbyHeroData hero = new LobbyHeroData();
                hero.UpdateData(response.PlayerDetail.HeroInfo[i]);
                heros.Add(hero);
            }
            playerDetails.Heroes = heros;
            playerDetails.HeroTeam = response.PlayerDetail.HeroTeamInfo.HeroType;
            GameEntry.Event.Fire(sender, playerDetails);
        }
    }
}
