//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// You may need to modify 'Handle' method.
// Don't modify the rest unless you know what you're doing.
//----------------------------------------------------------------------------------------------------

using GameFramework.Event;
using GameFramework.Network;

namespace Genesis.GameClient
{
    public class LCGetSinglePvpRankHandler : BasePacketHandler
    {
        public override int OpCode { get { return NetworkHelper.GetOpCode(PacketType.LobbyServerToClient, 1072); } }

        public override void Handle(object sender, Packet packet)
        {
            base.Handle(sender, packet);
            Handle(sender, packet as LCGetSinglePvpRank);
        }

        public static void Handle(object sender, LCGetSinglePvpRank response)
        {
            GameEntry.Data.SingleMatchData.SetScore(response.Score);
            GameEntry.Event.Fire(sender, new GetSinglePvpRankEventArgs(response.Score));
        }
    }
    public class GetSinglePvpRankEventArgs : GameEventArgs
    {
        public int Score { private set; get; }
        public GetSinglePvpRankEventArgs(int score)
        {
            Score = score;
        }

        public override int Id
        {
            get { return (int)EventId.GetRankData; }
        }
    }


}
