//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// You may need to modify 'Handle' method.
// Don't modify the rest unless you know what you're doing.
//----------------------------------------------------------------------------------------------------

using GameFramework.Network;

namespace Genesis.GameClient
{
    public class LCGetSinlgePVPRanksHandler : BasePacketHandler
    {
        public override int OpCode { get { return NetworkHelper.GetOpCode(PacketType.LobbyServerToClient, 5016); } }

        public override void Handle(object sender, Packet packet)
        {
            base.Handle(sender, packet);
            Handle(sender, packet as LCGetSinlgePVPRanks);
        }

        public static void Handle(object sender, LCGetSinlgePVPRanks response)
        {
            GameEntry.Event.Fire(sender, new GetSinglePvpRanksEventArgs(response));
        }
    }
}
