//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// You may need to modify 'Handle' method.
// Don't modify the rest unless you know what you're doing.
//----------------------------------------------------------------------------------------------------

using GameFramework.Network;

namespace Genesis.GameClient
{
    public class LCGetArenaPlayerAndTeamInfoHandler : BasePacketHandler
    {
        public override int OpCode { get { return NetworkHelper.GetOpCode(PacketType.LobbyServerToClient, 2301); } }

        public override void Handle(object sender, Packet packet)
        {
            base.Handle(sender, packet);
            Handle(sender, packet as LCGetArenaPlayerAndTeamInfo);
        }

        public static void Handle(object sender, LCGetArenaPlayerAndTeamInfo response)
        {
            GameEntry.Data.OfflineArena.UpdateEnermies(response);
            GameEntry.Event.Fire(sender, new OfflineArenaPlayerListChangedEventArgs());

            if (response.PlayerInfo != null)
            {
                GameEntry.Data.Player.UpdateData(response.PlayerInfo);
                GameEntry.Event.Fire(sender, new PlayerDataChangedEventArgs());
            }

            if (response.ArenaInfo != null)
            {
                GameEntry.Data.OfflineArena.UpdateArenaData(response.ArenaInfo);
                GameEntry.Event.Fire(sender, new OfflineArenaDataChangedEventArgs());
            }

        }
    }
}
