//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// You may need to modify 'Handle' method.
// Don't modify the rest unless you know what you're doing.
//----------------------------------------------------------------------------------------------------

using GameFramework.Network;

namespace Genesis.GameClient
{
    public class LCLeaveInstanceForResourceHandler : BasePacketHandler
    {
        public override int OpCode { get { return NetworkHelper.GetOpCode(PacketType.LobbyServerToClient, 2601); } }

        public override void Handle(object sender, Packet packet)
        {
            base.Handle(sender, packet);
            Handle(sender, packet as LCLeaveInstanceForResource);
        }

        public static void Handle(object sender, LCLeaveInstanceForResource response)
        {
            if (response.PlayerInfo != null)
            {
                GameEntry.Data.Player.UpdateData(response.PlayerInfo);
                GameEntry.Event.Fire(sender, new PlayerDataChangedEventArgs());
            }

            var helper = new RewardCollectionHelper();
            helper.AddCompoundItems(response.CompoundItemInfos);
            GameEntry.Event.Fire(sender, new LeaveInstanceForResourceResponseEventArgs(helper, response));
        }
    }
}
