//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// You may need to modify 'Handle' method.
// Don't modify the rest unless you know what you're doing.
//----------------------------------------------------------------------------------------------------

using GameFramework.Network;
using System.Collections.Generic;

namespace Genesis.GameClient
{
    public class LCLeaveInstanceHandler : BasePacketHandler
    {
        public override int OpCode { get { return NetworkHelper.GetOpCode(PacketType.LobbyServerToClient, 1005); } }

        public override void Handle(object sender, Packet packet)
        {
            base.Handle(sender, packet);
            LCLeaveInstance response = packet as LCLeaveInstance;
            GameEntry.Data.Player.UpdateData(response.PlayerInfo);
            for (int i = 0; i < response.LobbyHeroInfo.Count; i++)
            {
                LobbyHeroData data = GameEntry.Data.LobbyHeros.GetData(response.LobbyHeroInfo[i].Type);
                data.UpdateData(response.LobbyHeroInfo[i]);
            }

            if (response.ItemInfo != null)
            {
                List<PBItemInfo> instanceItems = new List<PBItemInfo>();
                for (int i = 0; i < response.ItemInfo.Count; i++)
                {
                    int count = response.ItemInfo[i].Count - GeneralItemUtility.GetGeneralItemCount(response.ItemInfo[i].Type);
                    instanceItems.Add(new PBItemInfo { Type = response.ItemInfo[i].Type, Count = count });
                }
                GameEntry.Data.InstanceGoods.ClearAndAddData(instanceItems);
                GeneralItemUtility.UpdateItemsData(response.ItemInfo);
            }

            if (response.Win)
            {
                InstanceProgressData instanceProgressData = GameEntry.Data.InstanceProgresses.GetData(response.InstanceType);
                if (instanceProgressData == null)
                {
                    GameEntry.Data.InstanceProgresses.AddData(new PBInstanceProgressInfo { Id = response.InstanceType, StarCount = response.StarCount });
                    GameEntry.Event.Fire(this, new InstanceProgressDataChangedEventArgs());
                }
                else if (response.StarCount > instanceProgressData.StarCount)
                {
                    instanceProgressData.UpdateData(new PBInstanceProgressInfo { Id = response.InstanceType, StarCount = response.StarCount });
                    GameEntry.Event.Fire(this, new InstanceProgressDataChangedEventArgs());
                }
            }

            GameEntry.Data.InstanceGroups.ModifyLevel(response.InstanceType);

            GameEntry.Event.Fire(this, new PlayerDataChangedEventArgs());
            GameEntry.Event.Fire(this, new LobbyHeroDataChangedEventArgs());
            GameEntry.Event.Fire(this, new ItemDataChangedEventArgs());
            GameEntry.Event.Fire(this, new HeroQualityItemDataChangeEventArgs());
            GameEntry.Event.Fire(this, new LeaveInstanceResponseEventArgs());
        }
    }
}
