//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// You may need to modify 'Handle' method.
// Don't modify the rest unless you know what you're doing.
//----------------------------------------------------------------------------------------------------

using GameFramework.Network;

namespace Genesis.GameClient
{
    public class LCNewGearQualityLevelUpHandler : BasePacketHandler
    {
        public override int OpCode { get { return NetworkHelper.GetOpCode(PacketType.LobbyServerToClient, 1404); } }

        public override void Handle(object sender, Packet packet)
        {
            base.Handle(sender, packet);
            Handle(sender, packet as LCNewGearQualityLevelUp);
        }

        public static void Handle(object sender, LCNewGearQualityLevelUp response)
        {
            var lobbyHero = GameEntry.Data.LobbyHeros.GetData(response.HeroInfo.Type);
            lobbyHero.UpdateData(response.HeroInfo);
            GeneralItemUtility.UpdateItemsData(response.ItemInfos);
            GameEntry.Data.Player.UpdateData(response.PlayerInfo);
            GameEntry.Event.Fire(sender, new PlayerDataChangedEventArgs());
            GameEntry.Event.Fire(sender, new LobbyHeroDataChangedEventArgs());
            GameEntry.Event.Fire(sender, new ItemDataChangedEventArgs());
            GameEntry.Event.Fire(sender, new NewGearQualityLevelUpEventArgs());
        }
    }
}
