//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// You may need to modify 'Handle' method.
// Don't modify the rest unless you know what you're doing.
//----------------------------------------------------------------------------------------------------

using GameFramework;
using GameFramework.Network;

namespace Genesis.GameClient
{
    public class LCPushPvpMatchSuccessHandler : BasePacketHandler
    {
        public override int OpCode { get { return NetworkHelper.GetOpCode(PacketType.LobbyServerToClient, 4001); } }

        public override void Handle(object sender, Packet packet)
        {
            base.Handle(sender, packet);
            //LCPushPvpMatchSuccess response = packet as LCPushPvpMatchSuccess;
            //GameEntry.Network.SetNetworkChannelConnection(Constant.Network.RoomNetworkChannelName, false, response.RoomServerHost, response.RoomServerPort);
            //GameEntry.Data.AddOrUpdateTempData(Constant.TempData.RoomId, response.RoomId);
            //GameEntry.Data.AddOrUpdateTempData(Constant.TempData.RoomServerToken, response.Token);

            //GameEntry.Data.PvpArenaOpponent.UpdateData(response.EnemyInfo);

            //GameEntry.Event.Fire(this, new PvpMatchingSuccessEventArgs(response.InstanceId));
            //Log.Info("Match PVP success, room id '{0}', server url '{1}:{2}'.", response.RoomId.ToString(), response.RoomServerHost, response.RoomServerPort.ToString());
        }
    }
}
