//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// You may need to modify 'Handle' method.
// Don't modify the rest unless you know what you're doing.
//----------------------------------------------------------------------------------------------------

using GameFramework.Network;

namespace Genesis.GameClient
{
    public class LCRefreshShopHandler : BasePacketHandler
    {
        public override int OpCode { get { return NetworkHelper.GetOpCode(PacketType.LobbyServerToClient, 1101); } }

        public override void Handle(object sender, Packet packet)
        {
            base.Handle(sender, packet);
            Handle(sender, packet as LCRefreshShop);
        }

        public static void Handle(object sender, LCRefreshShop response)
        {
            if (response.PlayerInfo != null)
            {
                GameEntry.Data.Player.UpdateData(response.PlayerInfo);
                GameEntry.Event.Fire(sender, new PlayerDataChangedEventArgs());
            }

            if (response.ShopInfo != null)
            {
                GameEntry.Data.ShopsData.UpdateData(response.ShopInfo);
                GameEntry.Event.Fire(sender, new ShopDataChangedEventArgs(response.ShopInfo.ShopType));
            }
        }
    }
}
