//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// You may need to modify 'Handle' method.
// Don't modify the rest unless you know what you're doing.
//----------------------------------------------------------------------------------------------------

using GameFramework.Network;

namespace Genesis.GameClient
{
    public class LCRemoveSkillBadgeHandler : BasePacketHandler
    {
        public override int OpCode { get { return NetworkHelper.GetOpCode(PacketType.LobbyServerToClient, 1407); } }

        public override void Handle(object sender, Packet packet)
        {
            base.Handle(sender, packet);
            Handle(sender, packet as LCRemoveSkillBadge);
            GameEntry.Event.Fire(this, new LobbyHeroDataChangedEventArgs());
            GameEntry.Event.Fire(this, new HeroSkillDataChangedEventArgs(HeroSkillDataChangedEventArgs.SkillChangeType.RemoveBadge));
        }

        public static void Handle(object sender, LCRemoveSkillBadge response)
        {
            var lobbyHeroData = GameEntry.Data.LobbyHeros.GetData(response.HeroInfo.Type);

            var badgeItems = GameEntry.Data.SkillBadgeItems;

            if (lobbyHeroData != null)
            {
                lobbyHeroData.UpdateData(response.HeroInfo);
            }

            var badgeItemData = badgeItems.GetData(response.BadgeItemInfo.Type);

            if (badgeItemData != null)
            {
                badgeItemData.UpdateData(response.BadgeItemInfo);
            }
            else
            {
                GameEntry.Data.SkillBadgeItems.AddData(response.BadgeItemInfo);
            }

            GameEntry.Data.Player.UpdateData(response.PlayerInfo);
            GameEntry.Event.Fire(sender, new PlayerDataChangedEventArgs());
            GameEntry.Event.Fire(sender, new LobbyHeroDataChangedEventArgs());
            GameEntry.Event.Fire(sender, new HeroSkillDataChangedEventArgs(HeroSkillDataChangedEventArgs.SkillChangeType.RemoveBadge));
        }
    }
}
