//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// You may need to modify 'Handle' method.
// Don't modify the rest unless you know what you're doing.
//----------------------------------------------------------------------------------------------------

using GameFramework.Network;

namespace Genesis.GameClient
{
    public class LCReceiveChatHandler : BasePacketHandler
    {
        public override int OpCode { get { return NetworkHelper.GetOpCode(PacketType.LobbyServerToClient, 3002); } }

        public override void Handle(object sender, Packet packet)
        {
            base.Handle(sender, packet);
            Handle(sender, packet as LCReceiveChat);
        }

        public static void Handle(object sender, LCReceiveChat response)
        {
            GameEntry.Data.Chat.UpdateData(response);
            GameEntry.Event.Fire(sender, new GetChatEventArgs(response));
        }
    }
}
