//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// You may need to modify 'Handle' method.
// Don't modify the rest unless you know what you're doing.
//----------------------------------------------------------------------------------------------------

using GameFramework.Network;

namespace Genesis.GameClient
{
    public class LCReceiveArenaRewardHandler : BasePacketHandler
    {
        public override int OpCode { get { return NetworkHelper.GetOpCode(PacketType.LobbyServerToClient, 2306); } }

        public override void Handle(object sender, Packet packet)
        {
            base.Handle(sender, packet);
            Handle(sender, packet as LCReceiveArenaReward);
        }

        public static void Handle(object sender, LCReceiveArenaReward response)
        {
            GameEntry.Data.OfflineArena.UpdateArenaRewardData(response.RewardType, true);

            GameEntry.Event.Fire(sender, new OfflineArenaDataChangedEventArgs());
        }
    }
}
