//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// You may need to modify 'Handle' method.
// Don't modify the rest unless you know what you're doing.
//----------------------------------------------------------------------------------------------------

using GameFramework.Network;

namespace Genesis.GameClient
{
    public class LCResetFriendEnergyHandler : BasePacketHandler
    {
        public override int OpCode { get { return NetworkHelper.GetOpCode(PacketType.LobbyServerToClient, 3108); } }

        public override void Handle(object sender, Packet packet)
        {
            base.Handle(sender, packet);
            Handle(sender, packet as LCResetFriendEnergy);
        }

        public static void Handle(object sender, LCResetFriendEnergy response)
        {
            GameEntry.Data.Friends.ModifyTodyClaimCount(response.FriendEnergy.TodayClaimCount);
            GameEntry.Data.Friends.ModifyTodayGiveCount(response.FriendEnergy.TodayGiveCount);

            GameEntry.Event.Fire(sender, new FriendDataChangedEventArgs(FriendDataChangedEventArgs.ChangeMode.ListRefreshed));
        }
    }
}
