//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// You may need to modify 'Handle' method.
// Don't modify the rest unless you know what you're doing.
//----------------------------------------------------------------------------------------------------

using GameFramework.Network;

namespace Genesis.GameClient
{
    public class LCSearchPlayersHandler : BasePacketHandler
    {
        public override int OpCode { get { return NetworkHelper.GetOpCode(PacketType.LobbyServerToClient, 3101); } }

        public override void Handle(object sender, Packet packet)
        {
            base.Handle(sender, packet);
            LCSearchPlayers response = packet as LCSearchPlayers;

            // Fake data for debugging.
            //for (int i = 0; i < 5; ++i)
            //{
            //    response.Players.Add(new PBPlayerInfo { Id = 1000 + i, Name = i + "Fake searched player".Substring(0, i + 2), Level = 20 + i, });
            //    response.IsMyFriend.Add(i % 3 == 0);
            //}

            GameEntry.Event.Fire(this, new SearchPlayersSuccessEventArgs(response));
        }
    }
}
