//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// You may need to modify 'Handle' method.
// Don't modify the rest unless you know what you're doing.
//----------------------------------------------------------------------------------------------------

using GameFramework.Network;

namespace Genesis.GameClient
{
    public class LCSendFriendRequestHandler : BasePacketHandler
    {
        public override int OpCode { get { return NetworkHelper.GetOpCode(PacketType.LobbyServerToClient, 3103); } }

        public override void Handle(object sender, Packet packet)
        {
            base.Handle(sender, packet);
            Handle(sender, packet as LCSendFriendRequest);
        }

        public static void Handle(object sender, LCSendFriendRequest response)
        {
            if (response.PlayerInfo.Id == GameEntry.Data.Player.Id)
            {
                // This is me
                GameEntry.UI.OpenUIForm(UIFormId.Toast, new ToastDisplayData { Message = GameEntry.Localization.GetString("UI_TEXT_FRIENDLIST_REQUEST_SENT") });
            }
            else
            {
                // This is the one who wanna add you as friend
                GameEntry.Data.FriendRequests.AddRequest(response.PlayerInfo);
                GameEntry.Event.Fire(sender, new FriendRequestSentEventArgs());
                GameEntry.Event.Fire(sender, new ReminderUpdatedEventArgs());
                GameEntry.Event.Fire(sender, new PendingFriendRequestsDataChangedEventArgs()); 
            }
        }
    }
}
