//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// You may need to modify 'Handle' method.
// Don't modify the rest unless you know what you're doing.
//----------------------------------------------------------------------------------------------------

using GameFramework.Network;

namespace Genesis.GameClient
{
    public class LCSynthesizeHeroQualityItemHandler : BasePacketHandler
    {
        public override int OpCode { get { return NetworkHelper.GetOpCode(PacketType.LobbyServerToClient, 1402); } }

        public override void Handle(object sender, Packet packet)
        {
            base.Handle(sender, packet);
            Handle(sender, packet as LCSynthesizeHeroQualityItem);
        }

        public static void Handle(object sender, LCSynthesizeHeroQualityItem response)
        {
            if (response.PlayerInfo != null)
            {
                GameEntry.Data.Player.UpdateData(response.PlayerInfo);
                GameEntry.Event.Fire(sender, new PlayerDataChangedEventArgs());
            }

            GeneralItemUtility.UpdateItemsData(response.HeroQualityItemInfos);
            GameEntry.Event.Fire(sender, new HeroQualityItemDataChangeEventArgs());
        }
    }
}
