//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// You may need to modify 'Handle' method.
// Don't modify the rest unless you know what you're doing.
//----------------------------------------------------------------------------------------------------

using GameFramework.Network;

namespace Genesis.GameClient
{
    public class LCUseHeroQualityItemHandler : BasePacketHandler
    {
        public override int OpCode { get { return NetworkHelper.GetOpCode(PacketType.LobbyServerToClient, 1401); } }

        public override void Handle(object sender, Packet packet)
        {
            base.Handle(sender, packet);
            Handle(sender, packet as LCUseHeroQualityItem);
        }

        public static void Handle(object sender, LCUseHeroQualityItem response)
        {
            GeneralItemUtility.UpdateItemsData(response.ItemInfos);
            GameEntry.Event.Fire(sender, new HeroQualityItemDataChangeEventArgs());
            GameEntry.Data.LobbyHeros.GetData(response.HeroInfo.Type).UpdateData(response.HeroInfo);
            GameEntry.Event.Fire(sender, new LobbyHeroDataChangedEventArgs());
            GameEntry.Data.Player.UpdateData(response.PlayerInfo);
            GameEntry.Event.Fire(sender, new PlayerDataChangedEventArgs());
        }
    }
}
