//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// You may need to modify 'Handle' method.
// Don't modify the rest unless you know what you're doing.
//----------------------------------------------------------------------------------------------------

using GameFramework.Network;
using UnityEngine;

namespace Genesis.GameClient
{
    public class RCPushEntityMoveHandler : BasePacketHandler
    {
        public override int OpCode { get { return NetworkHelper.GetOpCode(PacketType.RoomServerToClient, 4100); } }

        public override void Handle(object sender, Packet packet)
        {
            if (GameEntry.Data.Room.HasReconnected)
            {
                return;
            }
            base.Handle(sender, packet);
            RCPushEntityMove response = packet as RCPushEntityMove;
            if (GameEntry.SceneLogic.SinglePvpInstanceLogic.PlayerIsMe(response.PlayerId))
            {
                return;
            }

            GameEntry.Event.Fire(this, new OtherHeroMovingUpdateEventArgs(response.PlayerId, response.EntityId, new Vector2(response.Transform.PositionX, response.Transform.PositionY), response.Transform.Rotation));
        }
    }
}
