//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// You may need to modify 'Handle' method.
// Don't modify the rest unless you know what you're doing.
//----------------------------------------------------------------------------------------------------

using GameFramework;
using GameFramework.Network;

namespace Genesis.GameClient
{
    public class RCPushEntityAddBuffHandler : BasePacketHandler
    {
        public override int OpCode { get { return NetworkHelper.GetOpCode(PacketType.RoomServerToClient, 4108); } }

        public override void Handle(object sender, Packet packet)
        {
            if (GameEntry.Data.Room.HasReconnected)
            {
                return;
            }
            base.Handle(sender, packet);
            RCPushEntityAddBuff response = packet as RCPushEntityAddBuff;

            var origin = GameEntry.Entity.GetGameEntity(response.OriginEntityId);
            var target = GameEntry.Entity.GetGameEntity(response.TargetEntityId) as TargetableObject;

            GameEntry.RoomLogic.AddLog("RCPushEntityAddBuffHandler", "Begins");

            if (target == null)
            {
                Log.Info("Target entity '{0}' is invalid.", response.TargetEntityId);
                return;
            }

            if (origin == null && response.OriginEntityId > 0)
            {
                Log.Info("Origin entity '{0}' is invalid.", response.OriginEntityId);
                return;
            }

            for (int i = 0; i < response.Buffs.Count; ++i)
            {
                GameEntry.RoomLogic.AddLog("RCPushEntityAddBuffHandler", "BuffTypeId: {0}, OriginEntityId: {1}, TargetEntityId: {2}, Origin: {3}",
                    response.Buffs[i].BuffId, response.OriginEntityId.ToString(), response.TargetEntityId.ToString(), origin == null ? "null" : origin.ToString());
            }
            var buffPool = target.Data.BuffPool as OnlineBuffPool;
            if (buffPool == null)
            {
                Log.Info("BuffPool is not online .Target entity '{0}' is invalid.", response.TargetEntityId);
                return;
            }
            buffPool.AddBuffList(response.Buffs, target.Data);

            GameEntry.RoomLogic.AddLog("RCPushEntityAddBuffHandler", "Ends");
        }
    }
}
