//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// You may need to modify 'Handle' method.
// Don't modify the rest unless you know what you're doing.
//----------------------------------------------------------------------------------------------------

using GameFramework.Network;

namespace Genesis.GameClient
{
    public class RCPushEntityPerformSkillStartHandler : BasePacketHandler
    {
        public override int OpCode { get { return NetworkHelper.GetOpCode(PacketType.RoomServerToClient, 4101); } }

        public override void Handle(object sender, Packet packet)
        {
            if (GameEntry.Data.Room.HasReconnected)
            {
                return;
            }
            base.Handle(sender, packet);
            RCPushEntityPerformSkillStart response = packet as RCPushEntityPerformSkillStart;

            if (GameEntry.SceneLogic.SinglePvpInstanceLogic.PlayerIsMe(response.PlayerId))
            {
                return;
            }

            var heroCharacter = GameEntry.Entity.GetGameEntity(response.EntityId) as HeroCharacter;

            bool res = false;
            if (heroCharacter != null)
            {
                heroCharacter.Data.UpdateTransform(response.Transform);
                heroCharacter.UpdateTransform(response.Transform);

                // TODO: 在此回包中加入技能索引和释放方式。
                heroCharacter.Motion.PerformSkill(response.SkillId, -1 /* 技能索引 */, false, false, false, true, PerformSkillType.Click /* 释放方式 */);
                res = true;
            }

            GameEntry.RoomLogic.AddLog("RCPushEntityPerformSkillStartHandler", "PlayerId: {0}, EntityId: {1}, SkillId: {2}, Result: {3}", response.PlayerId.ToString(), response.EntityId.ToString(), response.SkillId.ToString(), res.ToString());
        }
    }
}
