//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// You may need to modify 'Handle' method.
// Don't modify the rest unless you know what you're doing.
//----------------------------------------------------------------------------------------------------

using GameFramework.Network;

namespace Genesis.GameClient
{
    public class RCPushRoomReadyHandler : BasePacketHandler
    {
        public override int OpCode { get { return NetworkHelper.GetOpCode(PacketType.RoomServerToClient, 4002); } }

        public override void Handle(object sender, Packet packet)
        {
            base.Handle(sender, packet);
            RCPushRoomReady response = packet as RCPushRoomReady;
            GameEntry.Data.Room.SetStartTime(response.StartTime);
            GameEntry.Event.Fire(this, new RoomDataChangedEventArgs());
            GameEntry.Event.Fire(this, new RoomReadyEventArgs());
        }
    }
}
